[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
dependsOn = ["setup"]
cmds = ["cp CHANGELOG.md backend/ 2>/dev/null || true", "cd backend && npm install"]

[start]
cmd = "cd backend && node index.js"
