const fs = require('fs');

// Spanish translations for common patterns and terms
const spanishPatterns = {
    // Common UI terms
    'Add': 'Agregar',
    'Edit': 'Editar',
    'Delete': 'Eliminar',
    'Save': 'Guardar',
    'Cancel': 'Cancelar',
    'Confirm': 'Confirmar',
    'Close': 'Cerrar',
    'Back': 'Volver',
    'Next': 'Siguiente',
    'Previous': 'Anterior',
    'Search': 'Buscar',
    'Settings': 'Configuración',
    'Title': 'Título',
    'Description': 'Descripción',
    'Name': 'Nombre',
    'Content': 'Contenido',
    'Category': 'Categoría',
    'Priority': 'Prioridad',
    'Status': 'Estado',
    'Date': 'Fecha',
    'Time': 'Hora',
    'Loading': 'Cargando',
    'Error': 'Error',
    'Success': 'Éxito',
    'Warning': 'Advertencia',
    'Info': 'Información',
    'Yes': 'Sí',
    'No': 'No',
    'OK': 'OK',
    'Done': 'Hecho',
    'List': 'Lista',
    'Empty': 'Vacío',
    'All': 'Todos',
    'None': 'Ninguno',
    'More': 'Más',
    'Less': 'Menos',
    'Send': 'Enviar',
    'Receive': 'Recibir',
    'Reply': 'Responder',
    'Forward': 'Reenviar',
    'Share': 'Compartir',
    'Copy': 'Copiar',
    'Paste': 'Pegar',
    'Cut': 'Cortar',
    'Undo': 'Deshacer',
    'Redo': 'Rehacer',
    'Refresh': 'Actualizar',
    'Retry': 'Reintentar',
    'Login': 'Iniciar sesión',
    'Logout': 'Cerrar sesión',
    'Sign Up': 'Registrarse',
    'Sign In': 'Iniciar sesión',
    'Sign Out': 'Cerrar sesión',
    'Email': 'Correo electrónico',
    'Password': 'Contraseña',
    'Username': 'Nombre de usuario',
    'Phone': 'Teléfono',
    'Address': 'Dirección',
    'Website': 'Sitio web',
    'Link': 'Enlace',
    'URL': 'URL',
    'Code': 'Código',
    'ID': 'ID',
    'Version': 'Versión',
    'Language': 'Idioma',
    'Help': 'Ayuda',
    'FAQ': 'Preguntas frecuentes',
    'About': 'Acerca de',
    'Contact': 'Contacto',
    'Support': 'Soporte',
    'Feedback': 'Comentarios',
    'Report': 'Reportar',
    'Submit': 'Enviar',
    'Apply': 'Aplicar',
    'Reset': 'Restablecer',
    'Clear': 'Limpiar',
    'Remove': 'Eliminar',
    'Skip': 'Omitir',
    'Continue': 'Continuar',
    'Start': 'Iniciar',
    'Stop': 'Detener',
    'Pause': 'Pausar',
    'Resume': 'Reanudar',
    'Finish': 'Finalizar',
    'Complete': 'Completar',
    'Pending': 'Pendiente',
    'Active': 'Activo',
    'Inactive': 'Inactivo',
    'Online': 'En línea',
    'Offline': 'Sin conexión',
    'Enabled': 'Habilitado',
    'Disabled': 'Deshabilitado',
    'Required': 'Requerido',
    'Optional': 'Opcional',
    'Read': 'Leer',
    'Write': 'Escribir',
    'Read More': 'Leer más',
    'Learn More': 'Más información',
    'Get Started': 'Comenzar',
    'Try Again': 'Intentar de nuevo',
    'Contact Us': 'Contáctenos',
    'Sign Up Free': 'Registrarse gratis',
    'Learn More': 'Más información',
    'Get Started Free': 'Comenzar gratis',
    'View All': 'Ver todo',
    'Show More': 'Mostrar más',
    'Show Less': 'Mostrar menos',
    'Sort By': 'Ordenar por',
    'Filter By': 'Filtrar por',
    'Group By': 'Agrupar por',
    'Select All': 'Seleccionar todo',
    'Select None': 'Seleccionar ninguno',
    'Select': 'Seleccionar',
    'Selected': 'Seleccionado',
    'Deselected': 'Deseleccionado',
    'Upload': 'Subir',
    'Download': 'Descargar',
    'Import': 'Importar',
    'Export': 'Exportar',
    'Preview': 'Vista previa',
    'Full Screen': 'Pantalla completa',
    'Exit Full Screen': 'Salir de pantalla completa',
    'Print': 'Imprimir',
    'Menu': 'Menú',
    'Options': 'Opciones',
    'Go to': 'Ir a',
    'Navigate to': 'Navegar a',
    'Open': 'Abrir',
    'Close': 'Cerrar',
    'Minimize': 'Minimizar',
    'Maximize': 'Maximizar',
    'Restore': 'Restaurar',
    'Move': 'Mover',
    'Resize': 'Redimensionar',
    'Drag to reorder': 'Arrastrar para reordenar',
    'Pin': 'Fijar',
    'Unpin': 'Desfijar',
    'Block': 'Bloquear',
    'Unblock': 'Desbloquear',
    'Mute': 'Silenciar',
    'Unmute': 'Activar sonido',
    'Hide': 'Ocultar',
    'Show': 'Mostrar',
    'Expand': 'Expandir',
    'Collapse': 'Contraer',
    'Lock': 'Bloquear',
    'Unlock': 'Desbloquear',
    'Edit': 'Editar',
    'Update': 'Actualizar',
    'Create': 'Crear',
    'Generate': 'Generar',
    'Duplicate': 'Duplicar',
    'Archive': 'Archivar',
    'Unarchive': 'Desarchivar',
    'Restore': 'Restaurar',
    'Permanent Delete': 'Eliminar permanentemente',
    'Move to': 'Mover a',
    'Copy to': 'Copiar a',
    'Rename': 'Renombrar',
    'Replace': 'Reemplazar',
    'Insert': 'Insertar',
    'Append': 'Agregar al final',
    'Prepend': 'Agregar al inicio',
    'Sort': 'Ordenar',
    'Reverse': 'Invertir',
    'Randomize': 'Aleatorizar',
    'Shuffle': 'Mezclar',
    'Filter': 'Filtrar',
    'Find': 'Buscar',
    'Replace': 'Reemplazar',
    'Match': 'Coincidencia',
    'No matches': 'Sin coincidencias',
    'Results': 'Resultados',
    'No results': 'Sin resultados',
    'Found': 'Encontrado',
    'Not found': 'No encontrado',
    'Total': 'Total',
    'Count': 'Cantidad',
    'Number': 'Número',
    'Amount': 'Monto',
    'Quantity': 'Cantidad',
    'Price': 'Precio',
    'Cost': 'Costo',
    'Free': 'Gratis',
    'Paid': 'De pago',
    'Premium': 'Premium',
    'Basic': 'Básico',
    'Pro': 'Pro',
    'Enterprise': 'Empresa',
    'Team': 'Equipo',
    'Personal': 'Personal',
    'Public': 'Público',
    'Private': 'Privado',
    'Shared': 'Compartido',
    'Hidden': 'Oculto',
    'Visible': 'Visible',
    'Published': 'Publicado',
    'Draft': 'Borrador',
    'Review': 'Revisar',
    'Approved': 'Aprobado',
    'Rejected': 'Rechazado',
    'Archived': 'Archivado',
    'Deleted': 'Eliminado',
    'Created': 'Creado',
    'Modified': 'Modificado',
    'Updated': 'Actualizado',
    'Changed': 'Cambiado',
    'Added': 'Agregado',
    'Removed': 'Eliminado',
    'Duplicated': 'Duplicado',
    'Merged': 'Combinado',
    'Split': 'Dividido',
    'Imported': 'Importado',
    'Exported': 'Exportado',
    'Submitted': 'Enviado',
    'Confirmed': 'Confirmado',
    'Cancelled': 'Cancelado',
    'Expired': 'Expirado',
    'In Progress': 'En progreso',
    'On Hold': 'En espera',
    'Completed': 'Completado',
    'Failed': 'Fallido',
    'Successful': 'Exitoso',
    'Unsuccessful': 'Sin éxito',
    'Warning': 'Advertencia',
    'Danger': 'Peligro',
    'Notice': 'Aviso',
    'Tip': 'Consejo',
    'Note': 'Nota',
    'Notes': 'Notas',
    'Comment': 'Comentario',
    'Comments': 'Comentarios',
    'Reply': 'Responder',
    'Replies': 'Respuestas',
    'Thread': 'Hilo',
    'Topic': 'Tema',
    'Post': 'Publicación',
    'Posts': 'Publicaciones',
    'Message': 'Mensaje',
    'Messages': 'Mensajes',
    'Notification': 'Notificación',
    'Notifications': 'Notificaciones',
    'Alert': 'Alerta',
    'Alerts': 'Alertas',
    'Reminder': 'Recordatorio',
    'Reminders': 'Recordatorios',
    'Schedule': 'Programación',
    'Scheduled': 'Programado',
    'Recurring': 'Recurrente',
    'Daily': 'Diario',
    'Weekly': 'Semanal',
    'Monthly': 'Mensual',
    'Yearly': 'Anual',
    'Hourly': 'Cada hora',
    'Minutes': 'Minutos',
    'Hours': 'Horas',
    'Days': 'Días',
    'Weeks': 'Semanas',
    'Months': 'Meses',
    'Years': 'Años',
    'Minute': 'Minuto',
    'Hour': 'Hora',
    'Day': 'Día',
    'Week': 'Semana',
    'Month': 'Mes',
    'Year': 'Año',
    'Today': 'Hoy',
    'Tomorrow': 'Mañana',
    'Yesterday': 'Ayer',
    'Now': 'Ahora',
    'Later': 'Más tarde',
    'Earlier': 'Antes',
    'Soon': 'Pronto',
    'Already': 'Ya',
    'Still': 'Todavía',
    'Yet': 'Aún',
    'Always': 'Siempre',
    'Never': 'Nunca',
    'Sometimes': 'A veces',
    'Usually': 'Usualmente',
    'Sometimes': 'A veces',
    'Often': 'A menudo',
    'Rarely': 'Rara vez',
    'Immediately': 'Inmediatamente',
    'Eventually': 'Eventualmente',
    'Finally': 'Finalmente',
    'Initially': 'Inicialmente',
    'Previously': 'Previamente',
    'Currently': 'Actualmente',
    'Recently': 'Recientemente',
    'Lately': 'Últimamente',
    'Formerly': 'Anteriormente',
    'Finally': 'Por último',
    'Last': 'Último',
    'First': 'Primero',
    'Next': 'Siguiente',
    'Previous': 'Anterior',
    'New': 'Nuevo',
    'Old': 'Antiguo',
    'Recent': 'Reciente',
    'Current': 'Actual',
    'Latest': 'Último',
    'Earliest': 'Más antiguo',
    'Default': 'Predeterminado',
    'Custom': 'Personalizado',
    'Auto': 'Automático',
    'Manual': 'Manual',
    'Automatic': 'Automático',
    'Manual': 'Manual',
    'Built-in': 'Integrado',
    'Custom': 'Personalizado',
    'User': 'Usuario',
    'Users': 'Usuarios',
    'Admin': 'Administrador',
    'Admins': 'Administradores',
    'Moderator': 'Moderador',
    'Moderators': 'Moderadores',
    'Guest': 'Invitado',
    'Guests': 'Invitados',
    'Member': 'Miembro',
    'Members': 'Miembros',
    'Owner': 'Propietario',
    'Owners': 'Propietarios',
    'Manager': 'Gerente',
    'Managers': 'Gerentes',
    'Developer': 'Desarrollador',
    'Developers': 'Desarrolladores',
    'Designer': 'Diseñador',
    'Designers': 'Diseñadores',
    'Tester': 'Probador',
    'Testers': 'Probadores',
    'Bot': 'Bot',
    'Bots': 'Bots',
    'Agent': 'Agente',
    'Agents': 'Agentes',
    'Account': 'Cuenta',
    'Accounts': 'Cuentas',
    'Profile': 'Perfil',
    'Profiles': 'Perfiles',
    'Avatar': 'Avatar',
    'Password': 'Contraseña',
    'Security': 'Seguridad',
    'Privacy': 'Privacidad',
    'Terms': 'Términos',
    'Conditions': 'Condiciones',
    'Policy': 'Política',
    'Agreement': 'Acuerdo',
    'Contract': 'Contrato',
    'License': 'Licencia',
    'Permit': 'Permiso',
    'Access': 'Acceso',
    'Permission': 'Permiso',
    'Role': 'Rol',
    'Roles': 'Roles',
    'Permission': 'Permiso',
    'Permissions': 'Permisos',
    'Grant': 'Otorgar',
    'Revoke': 'Revocar',
    'Allow': 'Permitir',
    'Deny': 'Denegar',
    'Authorize': 'Autorizar',
    'Authentication': 'Autenticación',
    'Authorization': 'Autorización',
    'Login': 'Iniciar sesión',
    'Logout': 'Cerrar sesión',
    'Sign Up': 'Registrarse',
    'Register': 'Registrarse',
    'Sign In': 'Iniciar sesión',
    'Sign Out': 'Cerrar sesión',
    'Forgot Password': '¿Olvidó su contraseña?',
    'Reset Password': 'Restablecer contraseña',
    'Change Password': 'Cambiar contraseña',
    'Confirm Password': 'Confirmar contraseña',
    'New Password': 'Nueva contraseña',
    'Current Password': 'Contraseña actual',
    'Device': 'Dispositivo',
    'Devices': 'Dispositivos',
    'Entity': 'Entidad',
    'Entities': 'Entidades',
    'Connection': 'Conexión',
    'Connections': 'Conexiones',
    'Connect': 'Conectar',
    'Disconnect': 'Desconectar',
    'Connected': 'Conectado',
    'Disconnected': 'Desconectado',
    'Sync': 'Sincronizar',
    'Syncing': 'Sincronizando',
    'Synchronized': 'Sincronizado',
    'Synchronize': 'Sincronizar',
    'Refresh': 'Actualizar',
    'Reload': 'Recargar',
    'Restart': 'Reiniciar',
    'Reboot': 'Reiniciar',
    'Shutdown': 'Apagar',
    'Power': 'Encendido',
    'Reboot': 'Reiniciar',
    'Startup': 'Inicio',
    'Shutdown': 'Apagado',
    'Running': 'Ejecutando',
    'Stopped': 'Detenido',
    'Paused': 'Pausado',
    'Resumed': 'Reanudado',
    'Starting': 'Iniciando',
    'Stopping': 'Deteniendo',
    'Mission': 'Misión',
    'Missions': 'Misiones',
    'Task': 'Tarea',
    'Tasks': 'Tareas',
    'Todo': 'Por hacer',
    'TODOs': 'Tareas',
    'TODO List': 'Lista de tareas',
    'Mission Control': 'Centro de control de misiones',
    'Dashboard': 'Panel de control',
    'Portal': 'Portal',
    'Web Portal': 'Portal web',
    'Landing': 'Página de inicio',
    'Landing Page': 'Página de inicio',
    'Home': 'Inicio',
    'Home Page': 'Página de inicio',
    'Chat': 'Chat',
    'Chats': 'Chats',
    'Conversation': 'Conversación',
    'Conversations': 'Conversaciones',
    'Message': 'Mensaje',
    'Messages': 'Mensajes',
    'Send Message': 'Enviar mensaje',
    'Receive Message': 'Recibir mensaje',
    'Voice': 'Voz',
    'Audio': 'Audio',
    'Video': 'Video',
    'Image': 'Imagen',
    'Images': 'Imágenes',
    'Photo': 'Foto',
    'Photos': 'Fotos',
    'Picture': 'Imagen',
    'Pictures': 'Imágenes',
    'File': 'Archivo',
    'Files': 'Archivos',
    'Document': 'Documento',
    'Documents': 'Documentos',
    'Attachment': 'Adjunto',
    'Attachments': 'Adjuntos',
    'Upload': 'Subir',
    'Download': 'Descargar',
    'Folder': 'Carpeta',
    'Folders': 'Carpetas',
    'Directory': 'Directorio',
    'Path': 'Ruta',
    'Location': 'Ubicación',
    'Storage': 'Almacenamiento',
    'Memory': 'Memoria',
    'Cache': 'Caché',
    'Database': 'Base de datos',
    'Server': 'Servidor',
    'Client': 'Cliente',
    'Network': 'Red',
    'Internet': 'Internet',
    'Web': 'Web',
    'API': 'API',
    'Application': 'Aplicación',
    'App': 'Aplicación',
    'Apps': 'Aplicaciones',
    'Application Programming Interface': 'Interfaz de programación de aplicaciones',
    'Software': 'Software',
    'Hardware': 'Hardware',
    'Platform': 'Plataforma',
    'System': 'Sistema',
    'Module': 'Módulo',
    'Component': 'Componente',
    'Service': 'Servicio',
    'Feature': 'Función',
    'Features': 'Funciones',
    'Function': 'Función',
    'Functions': 'Funciones',
    'Functionality': 'Funcionalidad',
    'Capability': 'Capacidad',
    'Capabilities': 'Capacidades',
    'Ability': 'Habilidad',
    'Option': 'Opción',
    'Options': 'Opciones',
    'Setting': 'Configuración',
    'Settings': 'Configuraciones',
    'Configuration': 'Configuración',
    'Configure': 'Configurar',
    'Setup': 'Configurar',
    'Initialize': 'Inicializar',
    'Install': 'Instalar',
    'Uninstall': 'Desinstalar',
    'Update': 'Actualizar',
    'Upgrade': 'Actualizar',
    'Downgrade': 'Degradar',
    'Install': 'Instalar',
    'Uninstall': 'Desinstalar',
    'Enable': 'Habilitar',
    'Disable': 'Deshabilitar',
    'Turn On': 'Encender',
    'Turn Off': 'Apagar',
    'Activate': 'Activar',
    'Deactivate': 'Desactivar',
    'Start': 'Iniciar',
    'End': 'Terminar',
    'Begin': 'Comenzar',
    'Finish': 'Finalizar',
    'Break': 'Descanso',
    'Continue': 'Continuar',
    'Pause': 'Pausar',
    'Resume': 'Reanudar',
    'Wait': 'Esperar',
    'Delay': 'Retraso',
    'Timeout': 'Tiempo de espera',
    'Interval': 'Intervalo',
    'Period': 'Período',
    'Cycle': 'Ciclo',
    'Loop': 'Bucle',
    'Step': 'Paso',
    'Steps': 'Pasos',
    'Stage': 'Etapa',
    'Phase': 'Fase',
    'Level': 'Nivel',
    'Progress': 'Progreso',
    'Percentage': 'Porcentaje',
    'Percent': 'Porcentaje',
    'Ratio': 'Relación',
    'Rate': 'Tasa',
    'Speed': 'Velocidad',
    'Fast': 'Rápido',
    'Slow': 'Lento',
    'Quick': 'Rápido',
    'Instant': 'Instantáneo',
    'Delayed': 'Retrasado',
    'Synchronous': 'Síncrono',
    'Asynchronous': 'Asíncrono',
    'Real-time': 'Tiempo real',
    'Background': 'Fondo',
    'Foreground': 'Primer plano',
    'Priority': 'Prioridad',
    'Urgent': 'Urgente',
    'High': 'Alto',
    'Medium': 'Medio',
    'Low': 'Bajo',
    'Normal': 'Normal',
    'Critical': 'Crítico',
    'Severe': 'Severo',
    'Major': 'Mayor',
    'Minor': 'Menor',
    'Trivial': 'Trivial',
    'Bug': 'Error',
    'Bugs': 'Errores',
    'Issue': 'Problema',
    'Issues': 'Problemas',
    'Problem': 'Problema',
    'Problems': 'Problemas',
    'Error': 'Error',
    'Errors': 'Errores',
    'Warning': 'Advertencia',
    'Warnings': 'Advertencias',
    'Notice': 'Aviso',
    'Info': 'Información',
    'Debug': 'Depurar',
    'Trace': 'Rastrear',
    'Log': 'Registro',
    'Logs': 'Registros',
    'History': 'Historial',
    'Recent': 'Reciente',
    'Timeline': 'Línea de tiempo',
    'Activity': 'Actividad',
    'Event': 'Evento',
    'Events': 'Eventos',
    'Action': 'Acción',
    'Actions': 'Acciones',
    'Operation': 'Operación',
    'Operations': 'Operaciones',
    'Process': 'Proceso',
    'Processing': 'Procesando',
    'Processed': 'Procesado',
    'Request': 'Solicitud',
    'Requests': 'Solicitudes',
    'Response': 'Respuesta',
    'Responses': 'Respuestas',
    'Query': 'Consulta',
    'Queries': 'Consultas',
    'Result': 'Resultado',
    'Results': 'Resultados',
    'Output': 'Salida',
    'Input': 'Entrada',
    'Data': 'Datos',
    'Value': 'Valor',
    'Values': 'Valores',
    'Key': 'Clave',
    'Keys': 'Claves',
    'Field': 'Campo',
    'Fields': 'Campos',
    'Record': 'Registro',
    'Records': 'Registros',
    'Row': 'Fila',
    'Rows': 'Filas',
    'Column': 'Columna',
    'Columns': 'Columnas',
    'Table': 'Tabla',
    'Entry': 'Entrada',
    'Entries': 'Entradas',
    'Item': 'Artículo',
    'Items': 'Artículos',
    'Object': 'Objeto',
    'Array': 'Arreglo',
    'List': 'Lista',
    'Map': 'Mapa',
    'Set': 'Conjunto',
    'Collection': 'Colección',
    'Structure': 'Estructura',
    'Format': 'Formato',
    'Type': 'Tipo',
    'Class': 'Clase',
    'Method': 'Método',
    'Function': 'Función',
    'Variable': 'Variable',
    'Constant': 'Constante',
    'Property': 'Propiedad',
    'Attribute': 'Atributo',
    'Tag': 'Etiqueta',
    'Tags': 'Etiquetas',
    'Label': 'Etiqueta',
    'Labels': 'Etiquetas',
    'Badge': 'Insignia',
    'Badge': 'Insignia',
    'Card': 'Tarjeta',
    'Cards': 'Tarjetas',
    'Widget': 'Widget',
    'Widgets': 'Widgets',
    'Button': 'Botón',
    'Buttons': 'Botones',
    'Link': 'Enlace',
    'Links': 'Enlaces',
    'Tab': 'Pestaña',
    'Tabs': 'Pestañas',
    'Panel': 'Panel',
    'Panels': 'Paneles',
    'Section': 'Sección',
    'Sections': 'Secciones',
    'Block': 'Bloque',
    'Blocks': 'Bloques',
    'Row': 'Fila',
    'Rows': 'Filas',
    'Column': 'Columna',
    'Columns': 'Columnas',
    'Grid': 'Cuadrícula',
    'Layout': 'Diseño',
    'Template': 'Plantilla',
    'Templates': 'Plantillas',
    'Theme': 'Tema',
    'Themes': 'Temas',
    'Style': 'Estilo',
    'Styles': 'Estilos',
    'Design': 'Diseño',
    'Color': 'Color',
    'Colors': 'Colores',
    'Background': 'Fondo',
    'Foreground': 'Primer plano',
    'Border': 'Borde',
    'Margin': 'Margen',
    'Padding': 'Relleno',
    'Spacing': 'Espaciado',
    'Size': 'Tamaño',
    'Width': 'Ancho',
    'Height': 'Alto',
    'Length': 'Largo',
    'Depth': 'Profundidad',
    'Radius': 'Radio',
    'Position': 'Posición',
    'Alignment': 'Alineación',
    'Align': 'Alinear',
    'Justify': 'Justificar',
    'Center': 'Centro',
    'Left': 'Izquierda',
    'Right': 'Derecha',
    'Top': 'Arriba',
    'Bottom': 'Abajo',
    'Middle': 'Medio',
    'Start': 'Inicio',
    'End': 'Fin',
    'Orientation': 'Orientación',
    'Horizontal': 'Horizontal',
    'Vertical': 'Vertical',
    'Landscape': 'Horizontal',
    'Portrait': 'Vertical',
    'Square': 'Cuadrado',
    'Circle': 'Círculo',
    'Triangle': 'Triángulo',
    'Rectangle': 'Rectángulo',
    'Polygon': 'Polígono',
    'Shape': 'Forma',
    'Icon': 'Icono',
    'Icons': 'Iconos',
    'Image': 'Imagen',
    'Images': 'Imágenes',
    'Photo': 'Foto',
    'Photos': 'Fotos',
    'Picture': 'Imagen',
    'Pictures': 'Imágenes',
    'Screenshot': 'Captura de pantalla',
    'Thumbnails': 'Miniaturas',
    'Preview': 'Vista previa',
    'Thumbnail': 'Minatura',
    'Avatar': 'Avatar',
    'Logo': 'Logo',
    'Symbol': 'Símbolo',
    'Emoji': 'Emoji',
    'Flag': 'Bandera',
    'Country': 'País',
    'Language': 'Idioma',
    'Locale': 'Configuración regional',
    'Timezone': 'Zona horaria',
    'Currency': 'Moneda',
    'Format': 'Formato',
    'Unit': 'Unidad',
    'Metric': 'Métrico',
    'Imperial': 'Imperial',
    'Standard': 'Estándar',
    'Metric': 'Métrico',
    'Temperature': 'Temperatura',
    'Celsius': 'Celsius',
    'Fahrenheit': 'Fahrenheit',
    'Kelvin': 'Kelvin',
    'Distance': 'Distancia',
    'Length': 'Longitud',
    'Weight': 'Peso',
    'Mass': 'Masa',
    'Volume': 'Volumen',
    'Area': 'Área',
    'Speed': 'Velocidad',
    'Velocity': 'Velocidad',
    'Acceleration': 'Aceleración',
    'Time': 'Tiempo',
    'Frequency': 'Frecuencia',
    'Wavelength': 'Longitud de onda',
    'Energy': 'Energía',
    'Power': 'Potencia',
    'Force': 'Fuerza',
    'Pressure': 'Presión',
    'Density': 'Densidad',
    'Viscosity': 'Viscosidad',
    'Concentration': 'Concentración',
    'Percentage': 'Porcentaje',
    'Ratio': 'Relación',
    'Fraction': 'Fracción',
    'Decimal': 'Decimal',
    'Integer': 'Entero',
    'Float': 'Flotante',
    'String': 'Cadena',
    'Text': 'Texto',
    'Number': 'Número',
    'Boolean': 'Booleano',
    'True': 'Verdadero',
    'False': 'Falso',
    'Null': 'Nulo',
    'Undefined': 'Indefinido',
    'Empty': 'Vacío',
    'Blank': 'En blanco',
    'Space': 'Espacio',
    'Character': 'Carácter',
    'Letter': 'Letra',
    'Digit': 'Dígito',
    'Number': 'Número',
    'Word': 'Palabra',
    'Sentence': 'Oración',
    'Paragraph': 'Párrafo',
    'Line': 'Línea',
    'Symbol': 'Símbolo',
    'Punctuation': 'Puntuación',
    'Capital': 'Capital',
    'Lowercase': 'Minúsculas',
    'Uppercase': 'Mayúsculas',
    'Title Case': 'Capitalizar',
    'Case Sensitive': 'Distingue mayúsculas',
    'Case Insensitive': 'No distingue mayúsculas',
    'Match': 'Coincidencia',
    'No match': 'Sin coincidencia',
    'Exact': 'Exacto',
    'Contains': 'Contiene',
    'Starts with': 'Comienza con',
    'Ends with': 'Termina con',
    'Includes': 'Incluye',
    'Excludes': 'Excluye',
    'Equals': 'Igual a',
    'Not equals': 'Diferente de',
    'Greater than': 'Mayor que',
    'Less than': 'Menor que',
    'Greater or equal': 'Mayor o igual',
    'Less or equal': 'Menor o igual',
    'Between': 'Entre',
    'In range': 'En rango',
    'Out of range': 'Fuera de rango',
    'Valid': 'Válido',
    'Invalid': 'Inválido',
    'Correct': 'Correcto',
    'Incorrect': 'Incorrecto',
    'Right': 'Correcto',
    'Wrong': 'Incorrecto',
    'Good': 'Bueno',
    'Bad': 'Malo',
    'Best': 'Mejor',
    'Worst': 'Peor',
    'Better': 'Mejor',
    'Worse': 'Peor',
    'Same': 'Igual',
    'Different': 'Diferente',
    'Similar': 'Similar',
    'Like': 'Como',
    'Unlike': 'A diferencia de',
    'Equal': 'Igual',
    'Equivalent': 'Equivalente',
    'Identical': 'Idéntico',
    'Unique': 'Único',
    'Duplicate': 'Duplicado',
    'Original': 'Original',
    'Copy': 'Copia',
    'Clone': 'Clon',
    'Replica': 'Réplica',
    'Version': 'Versión',
    'Revision': 'Revisión',
    'Update': 'Actualización',
    'Patch': 'Parche',
    'Hotfix': 'Corrección urgente',
    'Build': 'Construcción',
    'Compile': 'Compilar',
    'Link': 'Enlazar',
    'Deploy': 'Desplegar',
    'Release': 'Lanzar',
    'Publish': 'Publicar',
    'Unpublish': 'Despublicar',
    'Submit': 'Enviar',
    'Approve': 'Aprobar',
    'Reject': 'Rechazar',
    'Review': 'Revisar',
    'Preview': 'Vista previa',
    'Test': 'Probar',
    'Testing': 'Probando',
    'Tested': 'Probado',
    'Pass': 'Aprobar',
    'Fail': 'Fallar',
    'Success': 'Éxito',
    'Failure': 'Fracaso',
    'Error': 'Error',
    'Warning': 'Advertencia',
    'Info': 'Información',
    'Debug': 'Depurar',
    'Trace': 'Rastrear',
    'Log': 'Registro',
    'Audit': 'Auditoría',
    'Monitor': 'Monitorear',
    'Alert': 'Alerta',
    'Notify': 'Notificar',
    'Report': 'Reportar',
    'Analytics': 'Análisis',
    'Statistics': 'Estadísticas',
    'Metrics': 'Métricas',
    'KPIs': 'KPIs',
    'Goals': 'Objetivos',
    'Targets': 'Metas',
    'Benchmarks': 'Puntos de referencia',
    'Indicators': 'Indicadores',
    'Performance': 'Rendimiento',
    'Optimization': 'Optimización',
    'Improvement': 'Mejora',
    'Enhancement': 'Mejora',
    'Efficiency': 'Eficiencia',
    'Productivity': 'Productividad',
    'Reliability': 'Fiabilidad',
    'Availability': 'Disponibilidad',
    'Scalability': 'Escalabilidad',
    'Security': 'Seguridad',
    'Stability': 'Estabilidad',
    'Maintainability': 'Mantenibilidad',
    'Usability': 'Usabilidad',
    'Accessibility': 'Accesibilidad',
    'Compatibility': 'Compatibilidad',
    'Portability': 'Portabilidad',
    'Interoperability': 'Interoperabilidad',
    'Integration': 'Integración',
    'Customization': 'Personalización',
    'Configuration': 'Configuración',
    'Flexibility': 'Flexibilidad',
    'Modularity': 'Modularidad',
    'Reusability': 'Reutilización',
    'Maintainability': 'Mantenibilidad',
    'Readability': 'Legibilidad',
    'Clarity': 'Claridad',
    'Simplicity': 'Simplicidad',
    'Complexity': 'Complejidad',
    'Robustness': 'Robustez',
    'Resilience': 'Resiliencia',
    'Sustainability': 'Sostenibilidad',
    'Supportability': 'Capacidad de soporte',
    'Deployability': 'Capacidad de despliegue',
    'Testability': 'Capacidad de prueba',
    'Observability': 'Observabilidad',
    'Manageability': 'Capacidad de gestión',
    'Filtration': 'Filtración',
    'AI': 'IA',
    'Artificial Intelligence': 'Inteligencia artificial',
    'Machine Learning': 'Aprendizaje automático',
    'Deep Learning': 'Aprendizaje profundo',
    'Neural Network': 'Red neuronal',
    'Natural Language': 'Lenguaje natural',
    'NLP': 'PLN',
    'Computer Vision': 'Visión por computadora',
    'Speech Recognition': 'Reconocimiento de voz',
    'Text to Speech': 'Texto a voz',
    'TTS': 'TTS',
    'Chatbot': 'Chatbot',
    'Bot': 'Bot',
    'Agent': 'Agente',
    'Assistant': 'Asistente',
    'Automation': 'Automatización',
    'Workflow': 'Flujo de trabajo',
    'Pipeline': 'Tubería',
    'Orchestration': 'Orquestación',
    'Schedule': 'Programación',
    'Cron': 'Cron',
    'Timer': 'Temporizador',
    'Trigger': 'Disparador',
    'Event': 'Evento',
    'Webhook': 'Webhook',
    'API': 'API',
    'REST': 'REST',
    'GraphQL': 'GraphQL',
    'WebSocket': 'WebSocket',
    'Socket.IO': 'Socket.IO',
    'HTTP': 'HTTP',
    'HTTPS': 'HTTPS',
    'TCP': 'TCP',
    'UDP': 'UDP',
    'DNS': 'DNS',
    'URL': 'URL',
    'URI': 'URI',
    'Domain': 'Dominio',
    'Subdomain': 'Subdominio',
    'Host': 'Host',
    'Hostname': 'Nombre de host',
    'Port': 'Puerto',
    'Path': 'Ruta',
    'Query': 'Consulta',
    'Parameter': 'Parámetro',
    'Header': 'Encabezado',
    'Body': 'Cuerpo',
    'Request': 'Solicitud',
    'Response': 'Respuesta',
    'Status Code': 'Código de estado',
    'Success': 'Éxito',
    'Redirect': 'Redirección',
    'Client Error': 'Error del cliente',
    'Server Error': 'Error del servidor',
    'Redirect': 'Redirigir',
    'Permanent': 'Permanente',
    'Temporary': 'Temporal',
    'Cache': 'Caché',
    'Cookie': 'Galleta',
    'Session': 'Sesión',
    'Token': 'Token',
    'Authentication': 'Autenticación',
    'Authorization': 'Autorización',
    'Credential': 'Credencial',
    'Certificate': 'Certificado',
    'Key': 'Clave',
    'Secret': 'Secreto',
    'Password': 'Contraseña',
    'Encryption': 'Cifrado',
    'Decryption': 'Descifrado',
    'Hash': 'Hash',
    'Signature': 'Firma',
    'Verification': 'Verificación',
    'Validation': 'Validación',
    'Sanitization': 'Saneamiento',
    'Encoding': 'Codificación',
    'Decoding': 'Decodificación',
    'Compression': 'Compresión',
    'Decompression': 'Descompresión',
    'Serialization': 'Serialización',
    'Deserialization': 'Deserialización',
    'Parsing': 'Análisis',
    'Generation': 'Generación',
    'Rendering': 'Renderizado',
    'Execution': 'Ejecución',
    'Runtime': 'Tiempo de ejecución',
    'Compile Time': 'Tiempo de compilación',
    'Build Time': 'Tiempo de construcción',
    'Development': 'Desarrollo',
    'Production': 'Producción',
    'Testing': 'Pruebas',
    'Staging': 'Preparación',
    'QA': 'Control de calidad',
    'Debug': 'Depurar',
    'Release': 'Lanzamiento',
    'Deployment': 'Despliegue',
    'Installation': 'Instalación',
    'Configuration': 'Configuración',
    'Maintenance': 'Mantenimiento',
    'Monitoring': 'Monitoreo',
    'Recovery': 'Recuperación',
    'Backup': 'Copia de seguridad',
    'Restore': 'Restaurar',
    'Migration': 'Migración',
    'Upgrade': 'Actualización',
    'Downgrade': 'Degradación',
    'Rollback': 'Reversión',
    'Abort': 'Abortar',
    'Cancel': 'Cancelar',
    'Skip': 'Omitir',
    'Retry': 'Reintentar',
    'Ignore': 'Ignorar',
    'Handle': 'Manejar',
    'Process': 'Procesar',
    'Handle': 'Manejar',
    'Catch': 'Capturar',
    'Throw': 'Lanzar',
    'Error': 'Error',
    'Exception': 'Excepción',
    'Fault': 'Falla',
    'Failure': 'Fallo',
    'Crash': 'Bloqueo',
    'Hang': 'Bloqueo',
    'Slow': 'Lento',
    'Timeout': 'Tiempo de espera',
    'Deadlock': 'Interbloqueo',
    'Race Condition': 'Condición de carrera',
    'Memory Leak': 'Fuga de memoria',
    'Stack Overflow': 'Desbordamiento de pila',
    'Buffer Overflow': 'Desbordamiento de búfer',
    'Syntax Error': 'Error de sintaxis',
    'Runtime Error': 'Error de tiempo de ejecución',
    'Logical Error': 'Error lógico',
    'Semantic Error': 'Error semántico',
    'Type Error': 'Error de tipo',
    'Reference Error': 'Error de referencia',
    'Range Error': 'Error de rango',
    'URI Error': 'Error de URI',
    'Evaluation Error': 'Error de evaluación',
    'Internal Error': 'Error interno',
    'External Error': 'Error externo',
    'Network Error': 'Error de red',
    'Connection Error': 'Error de conexión',
    'Timeout Error': 'Error de tiempo de espera',
    'Permission Error': 'Error de permiso',
    'Not Found Error': 'Error no encontrado',
    'Already Exists Error': 'Error ya existe',
    'Invalid Input Error': 'Error de entrada inválida',
    'Validation Error': 'Error de validación',
    'Authentication Error': 'Error de autenticación',
    'Authorization Error': 'Error de autorización',
    'Rate Limit Error': 'Error de límite de tasa',
    'Quota Exceeded Error': 'Error de cuota excedida',
    'Service Unavailable Error': 'Error de servicio no disponible',
    'Gateway Timeout Error': 'Error de tiempo de espera del gateway',
    'Bad Gateway Error': 'Error de gateway incorrecto',
    'Conflict Error': 'Error de conflicto',
    'Precondition Failed Error': 'Error de precondición fallida',
    'Payload Too Large Error': 'Error de carga útil demasiado grande',
    'Unsupported Media Type Error': 'Error de tipo de medio no soportado',
    'Range Not Satisfiable Error': 'Error de rango no satisfacible',
    'Expectation Failed Error': 'Error de expectativa fallida',
    'Misdirected Request Error': 'Error de solicitud mal dirigida',
    'Unprocessable Entity Error': 'Error de entidad no procesable',
    'Locked Error': 'Error bloqueado',
    'Failed Dependency Error': 'Error de dependencia fallida',
    'Too Early Error': 'Error muy temprano',
    'Upgrade Required Error': 'Error de actualización requerida',
    'Precondition Required Error': 'Error de precondición requerida',
    'Too Many Requests Error': 'Error de demasiadas solicitudes',
    'Request Header Fields Too Large Error': 'Error de campos de encabezado de solicitud demasiado grandes',
    'Retry With Error': 'Error de reintento con',
    'Unavailable For Legal Reasons Error': 'Error no disponible por razones legales',
    'Destination Locked Error': 'Error de destino bloqueado',
    'Method Not Allowed Error': 'Error de método no permitido',
    'Not Acceptable Error': 'Error no aceptable',
    'Request Timeout Error': 'Error de tiempo de espera de solicitud',
    'Length Required Error': 'Error de longitud requerida',
    'Payload Too Large Error': 'Error de carga útil demasiado grande',
    'URI Too Long Error': 'Error de URI demasiado largo',
    'Unsupported Media Type Error': 'Error de tipo de medio no soportado',
    'Range Not Satisfiable Error': 'Error de rango no satisfacible',
    'Expectation Failed Error': 'Error de expectativa fallida',
    'I Am A Teapot Error': 'Error soy una tetera',
    'Authentication Timeout Error': 'Error de tiempo de espera de autenticación',
    'Loop Detected Error': 'Error de bucle detectado',
    'Not Extended Error': 'Error no extendido',
    'Network Authentication Required Error': 'Error de autenticación de red requerida',
    'Origin Error': 'Error de origen',
    ' SSL Error': 'Error de SSL',
    'TLS Error': 'Error de TLS',
    'Certificate Error': 'Error de certificado',
    'Certificate Expired Error': 'Error de certificado expirado',
    'Certificate Not Yet Valid Error': 'Error de certificado aún no válido',
    'Certificate Self-Signed Error': 'Error de certificado autofirmado',
    'Certificate Untrusted Error': 'Error de certificado no confiable',
    'Certificate Invalid Error': 'Error de certificado inválido',
    // Additional common translations
    'Are you sure': '¿Está seguro?',
    'Do you want to': '¿Desea',
    'Please enter': 'Por favor ingrese',
    'Please select': 'Por favor seleccione',
    'Enter your': 'Ingrese su',
    'Select your': 'Seleccione su',
    'Create your': 'Cree su',
    'Update your': 'Actualice su',
    'Forgot your': '¿Olvidó su',
    'Change your': 'Cambie su',
    'Welcome': 'Bienvenido',
    'Welcome back': 'Bienvenido de nuevo',
    'Goodbye': 'Adiós',
    'See you': 'Hasta luego',
    'Thank you': 'Gracias',
    'Thanks': 'Gracias',
    'Sorry': 'Lo siento',
    'Apologies': 'Disculpe',
    'Excuse me': 'Disculpe',
    'Please': 'Por favor',
    'Help': 'Ayuda',
    'Need help': '¿Necesita ayuda?',
    'How can I help': '¿Cómo puedo ayudar?',
    'What can I do': '¿Qué puedo hacer?',
    'Here you are': 'Aquí tiene',
    'There you go': 'Ahí tiene',
    'You are welcome': 'De nada',
    'My pleasure': 'Con mucho gusto',
    'No problem': 'Sin problema',
    'You got it': 'Entendido',
    'Alright': 'De acuerdo',
    'Okay': 'OK',
    'Sure': 'Claro',
    'Of course': 'Por supuesto',
    'Absolutely': 'Absolutamente',
    'Definitely': 'Definitivamente',
    'Indeed': 'Efectivamente',
    'Certainly': 'Ciertamente',
    'Exactly': 'Exacto',
    'Precisely': 'Precisamente',
    'Accurately': 'Con precisión',
    'Correctly': 'Correctamente',
    'Right away': 'De inmediato',
    'Right now': 'Ahora mismo',
    'As soon as possible': 'Lo antes posible',
    'At your convenience': 'Cuando le sea conveniente',
    'No rush': 'Sin prisa',
    'Take your time': 'Tómese su tiempo',
    'Whenever': 'Cuando quiera',
    'Whenever you want': 'Cuando quiera',
    'Any time': 'En cualquier momento',
    'Anytime': 'Cuando sea',
    'Right': 'Derecho',
    'Wrong': 'Incorrecto',
    'That is correct': 'Eso es correcto',
    'That is wrong': 'Eso es incorrecto',
    'I agree': 'Estoy de acuerdo',
    'I disagree': 'No estoy de acuerdo',
    'Maybe': 'Tal vez',
    'Perhaps': 'Quizás',
    'Possibly': 'Posiblemente',
    'Probably': 'Probablemente',
    'Definitely not': 'Definitivamente no',
    'Of course not': 'Por supuesto que no',
    'Absolutely not': 'Absolutamente no',
    'Not at all': 'En absoluto',
    'No way': 'De ninguna manera',
    'No thank you': 'No gracias',
    'Yes please': 'Sí por favor',
    'No thanks': 'No gracias',
    'Sounds good': 'Suena bien',
    'Looks good': 'Se ve bien',
    'Looks great': 'Se ve genial',
    'Fantastic': 'Fantástico',
    'Wonderful': 'Maravilloso',
    'Excellent': 'Excelente',
    'Great': 'Genial',
    'Good': 'Bueno',
    'Bad': 'Malo',
    'Terrible': 'Terrible',
    'Awful': 'Horrible',
    'Poor': 'Pobre',
    'Fair': 'Regular',
    'Average': 'Promedio',
    'Above average': 'Por encima del promedio',
    'Below average': 'Por debajo del promedio',
    'Expectation': 'Expectativa',
    'Unexpected': 'Inesperado',
    'As expected': 'Como se esperaba',
    'Better than expected': 'Mejor de lo esperado',
    'Worse than expected': 'Peor de lo esperado',
    'Surprise': 'Sorpresa',
    'Surprised': 'Sorprendido',
    'Not surprised': 'No sorprendido',
    'Interesting': 'Interesante',
    'Boring': 'Aburrido',
    'Exciting': 'Emocionante',
    'Amazing': 'Asombroso',
    'Awesome': 'Increíble',
    'Cool': 'Genial',
    'Nice': 'Bueno',
    'Lovely': 'Precioso',
    'Beautiful': 'Hermoso',
    'Pretty': 'Bonito',
    'ugly': 'Feo',
    'Handsome': 'Guapo',
    'Elegant': 'Elegante',
    'Simple': 'Simple',
    'Basic': 'Básico',
    'Advanced': 'Avanzado',
    'Professional': 'Profesional',
    'Personal': 'Personal',
    'Private': 'Privado',
    'Public': 'Público',
    'Secure': 'Seguro',
    'Insecure': 'Inseguro',
    'Safe': 'Seguro',
    'Dangerous': 'Peligroso',
    'Easy': 'Fácil',
    'Difficult': 'Difícil',
    'Hard': 'Duro',
    'Simple': 'Simple',
    'Complex': 'Complejo',
    'Complicated': 'Complicado',
    'Straightforward': 'Directo',
    'Challenging': 'Desafiante',
    'Impossible': 'Imposible',
    'Possible': 'Posible',
    'Probable': 'Probable',
    'Improbable': 'Improbable',
    'Likely': 'Probable',
    'Unlikely': 'Improbable',
    'Necessary': 'Necesario',
    'Unnecessary': 'Innecesario',
    'Required': 'Requerido',
    'Optional': 'Opcional',
    'Mandatory': 'Obligatorio',
    'Voluntary': 'Voluntario',
    'Important': 'Importante',
    'Unimportant': 'Sin importancia',
    'Urgent': 'Urgente',
    'Not urgent': 'No urgente',
    'Immediate': 'Inmediato',
    'Delayed': 'Retrasado',
    'Press': 'Presionar',
    'Press to': 'Presione para',
    'Click': 'Hacer clic',
    'Click to': 'Haga clic en',
    'Tap': 'Tocar',
    'Tap to': 'Toque para',
    'Swipe': 'Deslizar',
    'Swipe to': 'Deslice para',
    'Drag': 'Arrastrar',
    'Drag to': 'Arrastre para',
    'Drop': 'Soltar',
    'Drop here': 'Suelte aquí',
    'Scroll': 'Desplazar',
    'Scroll to': 'Desplácese a',
    'Zoom': 'Zoom',
    'Zoom in': 'Acercar',
    'Zoom out': 'Alejar',
    'Rotate': 'Rotar',
    'Flip': 'Voltear',
    'Copy': 'Copiar',
    'Cut': 'Cortar',
    'Paste': 'Pegar',
    'Duplicate': 'Duplicar',
    'Delete': 'Eliminar',
    'Remove': 'Eliminar',
    'Add': 'Agregar',
    'Insert': 'Insertar',
    'Append': 'Agregar',
    'Replace': 'Reemplazar',
    'Update': 'Actualizar',
    'Modify': 'Modificar',
    'Change': 'Cambiar',
    'Edit': 'Editar',
    'View': 'Ver',
    'Show': 'Mostrar',
    'Hide': 'Ocultar',
    'Display': 'Mostrar',
    'Exhibit': 'Exhibir',
    'Present': 'Presentar',
    'Preview': 'Vista previa',
    'Review': 'Revisar',
    'Browse': 'Explorar',
    'Explore': 'Explorar',
    'Discover': 'Descubrir',
    'Find': 'Encontrar',
    'Search': 'Buscar',
    'Look for': 'Buscar',
    'Locate': 'Localizar',
    'Navigate': 'Navegar',
    'Go to': 'Ir a',
    'Return to': 'Volver a',
    'Back to': 'Volver a',
    'Go back': 'Volver',
    'Forward': 'Adelante',
    'Back': 'Atrás',
    'Up': 'Arriba',
    'Down': 'Abajo',
    'Left': 'Izquierda',
    'Right': 'Derecha',
    'Next': 'Siguiente',
    'Previous': 'Anterior',
    'Continue': 'Continuar',
    'Stop': 'Detener',
    'Start': 'Iniciar',
    'Begin': 'Comenzar',
    'End': 'Terminar',
    'Finish': 'Finalizar',
    'Complete': 'Completar',
    'Done': 'Hecho',
    'Over': 'Terminado',
    'Under': 'Debajo',
    'Above': 'Encima',
    'Below': 'Debajo',
    'Between': 'Entre',
    'Among': 'Entre',
    'Inside': 'Dentro',
    'Outside': 'Fuera',
    'Within': 'Dentro de',
    'Without': 'Sin',
    'Through': 'A través de',
    'Across': 'Atraves de',
    'Along': 'A lo largo de',
    'Around': 'Alrededor de',
    'Near': 'Cerca de',
    'Far': 'Lejos de',
    'Close to': 'Cerca de',
    'Far from': 'Lejos de',
    'Next to': 'Al lado de',
    'Beside': 'Junto a',
    'Behind': 'Detrás de',
    'In front of': 'Enfrente de',
    'Opposite': 'Opuesto a',
    'Beyond': 'Más allá de',
    'Underneath': 'Debajo de',
    'Beneath': 'Bajo',
    'Over': 'Sobre',
    'On': 'En',
    'In': 'En',
    'At': 'En',
    'By': 'Por',
    'For': 'Para',
    'With': 'Con',
    'Without': 'Sin',
    'About': 'Acerca de',
    'Against': 'Contra',
    'Among': 'Entre',
    'Around': 'Alrededor de',
    'As': 'Como',
    'Because of': 'Debido a',
    'Before': 'Antes de',
    'After': 'Después de',
    'During': 'Durante',
    'Within': 'Dentro de',
    'Throughout': 'A lo largo de',
    'Until': 'Hasta',
    'Since': 'Desde',
    'Till': 'Hasta',
    'Toward': 'Hacia',
    'Towards': 'Hacia',
    'Away from': 'Lejos de',
    'Due to': 'Debido a',
    'Instead of': 'En lugar de',
    'In addition to': 'Además de',
    'In spite of': 'A pesar de',
    'Because': 'Porque',
    'Although': 'Aunque',
    'However': 'Sin embargo',
    'Nevertheless': 'No obstante',
    'Moreover': 'Además',
    'Furthermore': 'Además',
    'Additionally': 'Adicionalmente',
    'Besides': 'Además',
    'Otherwise': 'De lo contrario',
    'Therefore': 'Por lo tanto',
    'Thus': 'Así',
    'Hence': 'Por lo tanto',
    'Consequently': 'En consecuencia',
    'As a result': 'Como resultado',
    'For example': 'Por ejemplo',
    'For instance': 'Por ejemplo',
    'Such as': 'Tal como',
    'Including': 'Incluyendo',
    'Excluding': 'Excluyendo',
    'Regarding': 'Con respecto a',
    'Concerning': 'Concerniente a',
    'Relating to': 'Relativo a',
    'According to': 'Según',
    'Per': 'Por',
    'Via': 'Vía',
    'Using': 'Usando',
    'Used for': 'Usado para',
    'Designed for': 'Diseñado para',
    'Made of': 'Hecho de',
    'Made from': 'Hecho de',
    'Made with': 'Hecho con',
    'Consists of': 'Consiste en',
    'Contains': 'Contiene',
    'Including': 'Incluyendo',
    'Featuring': 'Presentando',
    'Powered by': 'Impulsado por',
    'Based on': 'Basado en',
    'Built on': 'Construido sobre',
    'According to': 'Según',
    'In accordance with': 'De acuerdo con',
    'In line with': 'En línea con',
    'In terms of': 'En términos de',
    'With regard to': 'Con respecto a',
    'As far as': 'Hasta donde',
    'As long as': 'Siempre que',
    'As soon as': 'Tan pronto como',
    'As well as': 'Así como',
    'At least': 'Al menos',
    'At most': 'A lo sumo',
    'At first': 'Al principio',
    'At last': 'Por último',
    'At the same time': 'Al mismo tiempo',
    'In the beginning': 'Al principio',
    'In the end': 'Al final',
    'On the other hand': 'Por otro lado',
    'On the contrary': 'Por el contrario',
    'In contrast': 'En contraste',
    'Compared to': 'Comparado con',
    'Compared with': 'Comparado con',
    'Unlike': 'A diferencia de',
    'Similar to': 'Similar a',
    'The same as': 'Lo mismo que',
    'Different from': 'Diferente de',
    'Identical to': 'Idéntico a',
    'Equal to': 'Igual a',
    'Equivalent to': 'Equivalente a',
    'Similar to': 'Similar a',
    'Like': 'Como',
    'Unlike': 'A diferencia de',
    'Rather than': 'En lugar de',
    'Instead of': 'En lugar de',
    'Rather': 'Mejor',
    'Fairly': 'Bastante',
    'Rather': 'Más bien',
    'Somewhat': 'Algo',
    'Quite': 'Bastante',
    'Pretty': 'Bastante',
    'Very': 'Muy',
    'Really': 'Realmente',
    'Extremely': 'Extremadamente',
    'Absolutely': 'Absolutamente',
    'Completely': 'Completamente',
    'Totally': 'Totalmente',
    'Entirely': 'Totalmente',
    'Fully': 'Completamente',
    'Partially': 'Parcialmente',
    'Partly': 'Parcialmente',
    'Mostly': 'Mayoritariamente',
    'Largely': 'En gran parte',
    'Mainly': 'Principalmente',
    'Primarily': 'Primariamente',
    'Chiefly': 'Principalmente',
    'Mostly': 'En su mayor parte',
    'Almost': 'Casi',
    'Nearly': 'Casi',
    'Approximately': 'Aproximadamente',
    'About': 'Cerca de',
    'Around': 'Alrededor de',
    'Roughly': 'Approximadamente',
    'Just about': 'Justo',
    'More or less': 'Más o menos',
    'Somewhere between': 'En algún lugar entre',
    'Exactly': 'Exacto',
    'Precisely': 'Precisamente',
    'Accurately': 'Con precisión',
    'Correctly': 'Correctamente',
    'In precisely': 'Precisamente',
    'In exactly': 'Exactamente',
    'In accurately': 'Con precisión',
    'No more than': 'No más de',
    'No less than': 'No menos de',
    'At exactly': 'En exactamente',
    'In the middle of': 'En el medio de',
    'In the center of': 'En el centro de',
    'In the middle': 'En el medio',
    'In the center': 'En el centro',
    'In between': 'En medio',
    'Halfway': 'A mitad de camino',
    'Side by side': 'Lado a lado',
    'Face to face': 'Cara a cara',
    'Hand in hand': 'De la mano',
    'Step by step': 'Paso a paso',
    'One by one': 'Uno por uno',
    'Bit by bit': 'Poco a poco',
    'Piece by piece': 'Pieza por pieza',
    'Little by little': 'Poco a poco',
    'Gradually': 'Gradualmente',
    'Slowly': 'Lentamente',
    'Quickly': 'Rapidamente',
    'Rapidly': 'Rapidamente',
    'Swiftly': ' Rápidamente',
    'Promptly': 'Prontamente',
    'Immediately': 'Inmediatamente',
    'Instantly': 'Instantáneamente',
    'Suddenly': 'De repente',
    'All at once': 'De golpe',
    'At once': 'De inmediato',
    'Right away': 'De inmediato',
    'Right now': 'Ahora mismo',
    'Now': 'Ahora',
    'Then': 'Entonces',
    'Later': 'Más tarde',
    'Eventually': 'Eventualmente',
    'Finally': 'Finalmente',
    'At last': 'Por fin',
    'In the end': 'Al final',
    'To sum up': 'En resumen',
    'In conclusion': 'En conclusión',
    'All in all': 'En definitiva',
    'On the whole': 'En general',
    'Generally': 'Generalmente',
    'Usually': 'Usualmente',
    'Typically': 'Típicamente',
    'Ordinarily': 'Ordinariamente',
    'Normally': 'Normalmente',
    'Regularly': 'Regularmente',
    'Often': 'A menudo',
    'Frequently': 'Frecuentemente',
    'Sometimes': 'A veces',
    'Occasionally': 'Ocasionalmente',
    'Rarely': 'Rara vez',
    'Seldom': 'Rara vez',
    'Almost never': 'Casi nunca',
    'Hardly ever': 'Apenas',
    'Never': 'Nunca',
    'Always': 'Siempre',
    'Usually': 'Usualmente',
    'Constantly': 'Constantemente',
    'Continuously': 'Continuamente',
    'Endlessly': 'Sin fin',
    'Forever': 'Para siempre',
    'Ongoing': 'En curso',
    'Ongoing': 'En progreso',
    'Currently': 'Actualmente',
    'Presently': 'Actualmente',
    'Now': 'Ahora',
    'At present': 'En la actualidad',
    'These days': 'Hoy en día',
    'Today': 'Hoy',
    'Nowdays': 'Hoy en día',
    'In this day and age': 'En esta época',
    'Lately': 'Últimamente',
    'Recently': 'Recientemente',
    'Of late': 'De un tiempo a esta parte',
    'In recent times': 'En tiempos recientes',
    'In times gone by': 'En tiempos pasados',
    'In the past': 'En el pasado',
    'In former times': 'En otros tiempos',
    'In the old days': 'En los viejos tiempos',
    'Once upon a time': 'Había una vez',
    'Long ago': 'Hace mucho tiempo',
    'A long time ago': 'Hace mucho tiempo',
    'Years ago': 'Hace años',
    'Back then': 'En aquel entonces',
    'At that time': 'En ese momento',
    'In those days': 'En aquellos días',
    'From now on': 'De ahora en adelante',
    'From this day forward': 'De hoy en adelante',
    'Starting today': 'Comenzando hoy',
    'Hereafter': 'De ahora en adelante',
    'Henceforth': 'De ahora en adelante',
    'Thereafter': 'Después de eso',
    'Afterward': 'Después',
    'After that': 'Después de eso',
    'Subsequently': 'Subsecuentemente',
    'Later on': 'Más tarde',
    'Eventually': 'Eventualmente',
    'Next': 'Siguiente',
    'Then': 'Entonces',
    'Following': 'Siguiente',
    'Before': 'Antes',
    'Prior to': 'Antes de',
    'Ahead of': 'Antes de',
    'In advance': 'Con anticipación',
    'Beforehand': 'Previamente',
    'Previously': 'Previamente',
    'Until now': 'Hasta ahora',
    'Up to now': 'Hasta ahora',
    'So far': 'Hasta ahora',
    'Until now': 'Hasta el momento',
    'As of now': 'Hasta ahora',
    'From this point': 'Desde este punto',
    'Hence': 'Por lo tanto',
    'From now on': 'De ahora en adelante',
    'Starting now': 'Comenzando ahora',
    'This is': 'Esto es',
    'That is': 'Eso es',
    'These are': 'Estos son',
    'Those are': 'Esos son',
    'Here is': 'Aquí está',
    'There is': 'Hay',
    'Here are': 'Aquí están',
    'There are': 'Hay',
    'This has': 'Esto tiene',
    'That has': 'Eso tiene',
    'These have': 'Estos tienen',
    'Those have': 'Esos tienen',
    'There is a': 'Hay un',
    'There are some': 'Hay algunos',
    'There is no': 'No hay',
    'There are no': 'No hay',
    'Is there': '¿Hay',
    'Are there': '¿Hay',
    'Was there': '¿Hubo',
    'Were there': '¿Hubo',
    'There will be': 'Habrá',
    'There would be': 'Habría',
    'There should be': 'Debería haber',
    'There can be': 'Puede haber',
    'There could be': 'Podría haber',
    'There may be': 'Puede haber',
    'There might be': 'Podría haber',
    'It is': 'Es',
    'It is a': 'Es un',
    'It is an': 'Es un',
    'It is the': 'Es el',
    'This is a': 'Esto es un',
    'This is an': 'Esto es un',
    'This is the': 'Esto es el',
    'That is a': 'Eso es un',
    'That is an': 'Eso es un',
    'That is the': 'Eso es el',
    'It is not': 'No es',
    'It is not a': 'No es un',
    'It is not an': 'No es un',
    'It is not the': 'No es el',
    'This is not': 'Esto no es',
    'That is not': 'Eso no es',
    'Is it': '¿Es',
    'Is it a': '¿Es un',
    'Is it an': '¿Es un',
    'Is it the': '¿Es el',
    'Is it not': '¿No es',
    'Is this': '¿Es esto',
    'Is that': '¿Es eso',
    'Is this a': '¿Es esto un',
    'Is that a': '¿Es eso un',
    'It seems': 'Parece',
    'It seems that': 'Parece que',
    'It appears': 'Aparece',
    'It appears that': 'Parece que',
    'It looks like': 'Parece que',
    'It looks as if': 'Parece que',
    'It feels like': 'Se siente como',
    'I think': 'Creo',
    'I think that': 'Creo que',
    'I believe': 'Creo',
    'I believe that': 'Creo que',
    'I suppose': 'Supongo',
    'I suppose that': 'Supongo que',
    'I guess': 'Supongo',
    'I guess that': 'Supongo que',
    'In my opinion': 'En mi opinión',
    'To my mind': 'Para mi',
    'As far as I am concerned': 'En lo que a mí respecta',
    'As for me': 'En cuanto a mí',
    'For my part': 'Por mi parte',
    'I reckon': 'Yo calculo',
    'I consider': 'Considero',
    'I feel': 'Siento',
    'I feel that': 'Siento que',
    'I am sure': 'Estoy seguro',
    'I am certain': 'Estoy seguro',
    'I am positive': 'Estoy seguro',
    'Definitely': 'Definitivamente',
    'For certain': 'Por seguro',
    'Without a doubt': 'Sin duda',
    'Of course': 'Por supuesto',
    'Certainly': 'Ciertamente',
    'Obviously': 'Obviamente',
    'Clearly': 'Claramente',
    'Evidently': 'Evidentemente',
    'Apparently': 'Aparentemente',
    'Seemingly': 'Parecidamente',
    'Plainly': 'Llanamente',
    'Simply': 'Simplemente',
    'Just': 'Solo',
    'Only': 'Solo',
    'Merely': 'Solo',
    'Purely': 'Puramente',
    'Entirely': 'Totalmente',
    'Solely': 'Solamente',
    'Exclusively': 'Exclusivamente',
    'Precisely': 'Precisamente',
    'Exactly': 'Exacto',
    'Just exactly': 'Exactamente',
    'Right': 'Derecho',
    'Directly': 'Directamente',
    'Straight': 'Recto',
    'Here': 'Aquí',
    'There': 'Allí',
    'Everywhere': 'En todas partes',
    'Somewhere': 'En algún lugar',
    'Anywhere': 'En cualquier lugar',
    'Nowhere': 'En ninguna parte',
    'Where': 'Dónde',
    'Wherever': 'Donde sea',
    'Someplace': 'Algún lugar',
    'Anyplace': 'Cualquier lugar',
    'Everyplace': 'Todos los lugares',
    'A place': 'Un lugar',
    'No place': 'Ningún lugar',
    'From here': 'Desde aquí',
    'From there': 'Desde allí',
    'To here': 'Aquí',
    'There': 'Allí',
    'This way': 'Por aquí',
    'That way': 'Por allí',
    'Another way': 'Otra manera',
    'One way': 'Una manera',
    'Some way': 'Alguna manera',
    'Any way': 'Cualquier manera',
    'No way': 'Ninguna manera',
    'How': 'Cómo',
    'However': 'Sin embargo',
    'Whatever': 'Lo que sea',
    'What': 'Qué',
    'Which': 'Cuál',
    'Who': 'Quién',
    'Whom': 'Quién',
    'Whose': 'De quién',
    'Why': 'Por qué',
    'When': 'Cuándo',
    'Where': 'Dónde',
    'Are': 'Son',
    'Is': 'Es',
    'Was': 'Fue',
    'Were': 'Fueron',
    'Been': 'Sido',
    'Being': 'Siendo',
    'Have': 'Han',
    'Has': 'Ha',
    'Had': 'Había',
    'Having': 'Teniendo',
    'Do': 'Hacen',
    'Does': 'Hace',
    'Did': 'Hizo',
    'Done': 'Hecho',
    'Doing': 'Haciendo',
    'Can': 'Puede',
    'Could': 'Podría',
    'May': 'Puede',
    'Might': 'Podría',
    'Must': 'Debe',
    'Shall': 'Deberá',
    'Should': 'Debería',
    'Would': 'Would',
    'Will': 'Will',
    'Would': 'Would',
    'Need': 'Necesita',
    'Needs': 'Necesita',
    'Needed': 'Necesitado',
    'Needing': 'Necesitando',
    'Want': 'Quiere',
    'Wants': 'Quiere',
    'Wanted': 'Querido',
    'Wanting': 'Queriendo',
    'Like': 'Gustar',
    'Likes': 'Gustos',
    'Liked': 'Gustado',
    'Liking': 'Gustando',
    'Prefer': 'Preferir',
    'Prefers': 'Prefiere',
    'Preferred': 'Preferido',
    'Preferring': 'Prefiriendo',
    'Wish': 'Desear',
    'Wishes': 'Deseos',
    'Wished': 'Deseado',
    'Wishing': 'Deseando',
    'Hope': 'Esperar',
    'Hopes': 'Espera',
    'Hoped': 'Esperó',
    'Hoping': 'Esperando',
    'Expect': 'Expectativa',
    'Expects': 'Espera',
    'Expected': 'Esperado',
    'Expecting': 'Esperando',
    'A': 'Un',
    'An': 'Un',
    'The': 'El',
    'Some': 'Algunos',
    'Any': 'Cualquier',
    'No': 'Ningún',
    'None': 'Ninguno',
    'Every': 'Cada',
    'All': 'Todos',
    'Both': 'Ambos',
    'Half': 'Mitad',
    'Either': 'Cualquiera',
    'Neither': 'Ninguno',
    'One': 'Uno',
    'Two': 'Dos',
    'Three': 'Tres',
    'Four': 'Cuatro',
    'Five': 'Cinco',
    'Six': 'Seis',
    'Seven': 'Siete',
    'Eight': 'Ocho',
    'Nine': 'Nueve',
    'Ten': 'Diez',
    'Zero': 'Cero',
    'First': 'Primero',
    'Second': 'Segundo',
    'Third': 'Tercero',
    'Fourth': 'Cuarto',
    'Fifth': 'Quinto',
    'Sixth': 'Sexto',
    'Seventh': 'Séptimo',
    'Eighth': 'Octavo',
    'Ninth': 'Noveno',
    'Tenth': 'Décimo',
    'Last': 'Último',
    'Next': 'Siguiente',
    'Previous': 'Anterior',
    'This': 'Esto',
    'That': 'Eso',
    'These': 'Estos',
    'Those': 'Esos',
    'Here': 'Aquí',
    'There': 'Allí',
    'When': 'Cuándo',
    'Where': 'Dónde',
    'Why': 'Por qué',
    'How': 'Cómo',
    'What': 'Qué',
    'Which': 'Cuál',
    'Who': 'Quién',
    'Whom': 'A quién',
    'Whose': 'De quién',
    'And': 'Y',
    'But': 'Pero',
    'Or': 'O',
    'Nor': 'Ni',
    'Yet': 'Aún',
    'So': 'Así',
    'Although': 'Aunque',
    'Because': 'Porque',
    'Since': 'Ya que',
    'While': 'Mientras',
    'If': 'Si',
    'Unless': 'A menos que',
    'Until': 'Hasta que',
    'When': 'Cuando',
    'Whenever': 'Cuando sea',
    'Where': 'Donde',
    'Wherever': 'Donde sea',
    'Whether': 'Si',
    'While': 'Mientras',
    'After': 'Después',
    'Before': 'Antes',
    'During': 'Durante',
    'Between': 'Entre',
    'Under': 'Bajo',
    'Over': 'Sobre',
    'Through': 'A través de',
    'Across': 'Atravesar',
    'Against': 'Contra',
    'Along': 'A lo largo',
    'Around': 'Alrededor',
    'Beyond': 'Más allá',
    'Near': 'Cerca',
    'Off': 'Apagado',
    'Onto': 'Encima de',
    'Out': 'Fuera',
    'Past': 'Pasado',
    'Than': 'Que',
    'Till': 'Hasta',
    'Toward': 'Hacia',
    'Under': 'Bajo',
    'Up': 'Arriba',
    'Upon': 'Sobre',
    'With': 'Con',
    'Within': 'Dentro',
    'Without': 'Sin',
    'I': 'Yo',
    'Me': 'Me',
    'My': 'Mi',
    'Mine': 'Mío',
    'Myself': 'Yo mismo',
    'We': 'Nosotros',
    'Us': 'Nos',
    'Our': 'Nuestro',
    'Ours': 'Nuestro',
    'Ourselves': 'Nosotros mismos',
    'You': 'Tú',
    'Your': 'Tu',
    'Yours': 'Tuyo',
    'Yourself': 'Tú mismo',
    'Yourselves': 'Ustedes mismos',
    'He': 'Él',
    'Him': 'Lo',
    'His': 'Su',
    'Himself': 'Él mismo',
    'She': 'Ella',
    'Her': 'La',
    'Hers': 'Suya',
    'Herself': 'Ella misma',
    'It': 'Eso',
    'Its': 'Su',
    'Itself': 'Sí mismo',
    'They': 'Ellos',
    'Them': 'Los',
    'Their': 'Su',
    'Theirs': 'Suyo',
    'Themselves': 'Ellos mismos',
    'What': 'Qué',
    'Whatever': 'Lo que sea',
    'Which': 'Cuál',
    'Whichever': 'El que sea',
    'Who': 'Quién',
    'Whoever': 'Quien sea',
    'Whom': 'A quién',
    'Whomever': 'A quien sea',
    'Whose': 'De quién',
    'Whosesoever': 'De quien sea',
    'A2A Protocol': 'Protocolo A2A',
    'Agent-to-Agent': 'Agente a Agente',
    'Chatbot': 'Chatbot',
    'Webhook': 'Webhook',
    'Mission Control': 'Centro de Misiones',
    'Soul': 'Alma',
    'Souls': 'Almas',
    'Rule': 'Regla',
    'Rules': 'Reglas',
    'Skill': 'Habilidad',
    'Skills': 'Habilidades',
    'Variable': 'Variable',
    'Variables': 'Variables',
    'Note': 'Nota',
    'Notes': 'Notas',
    'TODO': 'Por hacer',
    'TODOs': 'Tareas',
    'Mission': 'Misión',
    'Missions': 'Misiones',
    'Entity': 'Entidad',
    'Entities': 'Entidades',
    'Device': 'Dispositivo',
    'Devices': 'Dispositivos',
    'Slot': 'Ranura',
    'Slots': 'Ranuras',
    'Card': 'Tarjeta',
    'Cards': 'Tarjetas',
    'Code': 'Código',
    'Codes': 'Códigos',
    'Binding': 'Vinculación',
    'Bind': 'Vincular',
    'Unbind': 'Desvincular',
    'Bound': 'Vinculado',
    'Connect': 'Conectar',
    'Connection': 'Conexión',
    'Disconnect': 'Desconectar',
    'Sync': 'Sincronizar',
    'Syncing': 'Sincronizando',
    'Synchronized': 'Sincronizado',
    'Broadcast': 'Difusión',
    'Send': 'Enviar',
    'Receive': 'Recibir',
    'Message': 'Mensaje',
    'Messages': 'Mensajes',
    'Notification': 'Notificación',
    'Notifications': 'Notificaciones',
    'Reminder': 'Recordatorio',
    'Schedule': 'Programación',
    'Scheduled': 'Programado',
    'Timer': 'Temporizador',
    'Trigger': 'Disparador',
    'Workflow': 'Flujo de trabajo',
    'Automation': 'Automatización',
    'Token': 'Token',
    'Session': 'Sesión',
    'Credential': 'Credencial',
    'Credentials': 'Credenciales',
    'API Key': 'Clave API',
    'Secret': 'Secreto',
    'Channel': 'Canal',
    'Channels': 'Canales',
    'Plugin': 'Plugin',
    'Plugins': 'Plugins',
    'Gateway': 'Gateway',
    'Proxy': 'Proxy',
    'Portal': 'Portal',
    'Dashboard': 'Panel',
    'Widget': 'Widget',
    'Template': 'Plantilla',
    'Templates': 'Plantillas',
    'Guide': 'Guía',
    'Guides': 'Guías',
    'Tutorial': 'Tutorial',
    'Documentation': 'Documentación',
    'Docs': 'Docs',
    'FAQ': 'Preguntas frecuentes',
    'Help': 'Ayuda',
    'Support': 'Soporte',
    'Community': 'Comunidad',
    'Forum': 'Foro',
    'Contact': 'Contacto',
    'Feedback': 'Comentarios',
    'Bug Report': 'Reporte de error',
    'Feature Request': 'Solicitud de función',
    'Question': 'Pregunta',
    'Issue': 'Problema',
    'Problem': 'Problema',
    'Error': 'Error',
    'Warning': 'Advertencia',
    'Success': 'Éxito',
    'Info': 'Información',
    'Log': 'Registro',
    'Debug': 'Depurar',
    'Trace': 'Rastrear',
    'Profile': 'Perfil',
    'Account': 'Cuenta',
    'Settings': 'Configuración',
    'Preferences': 'Preferencias',
    'Privacy': 'Privacidad',
    'Security': 'Seguridad',
    'Password': 'Contraseña',
    'Email': 'Correo',
    'Subscription': 'Suscripción',
    'Plan': 'Plan',
    'Upgrade': 'Actualizar',
    'Downgrade': 'Degradar',
    'Cancel': 'Cancelar',
    'Renew': 'Renovar',
    'Expired': 'Expirado',
    'Expires': 'Expira',
    'Trial': 'Prueba',
    'Free': 'Gratis',
    'Paid': 'De pago',
    'Premium': 'Premium',
    'Enterprise': 'Empresa',
    'Pro': 'Pro',
    'Team': 'Equipo',
    'Personal': 'Personal',
    'Storage': 'Almacenamiento',
    'Usage': 'Uso',
    'Limit': 'Límite',
    'Quota': 'Cuota',
    'Bandwidth': 'Ancho de banda',
    'Request': 'Solicitud',
    'Response': 'Respuesta',
    'Timeout': 'Tiempo de espera',
    'Rate Limit': 'Límite de tasa',
    'Retry': 'Reintentar',
    'Failed': 'Fallido',
    'Success': 'Éxito',
    'Pending': 'Pendiente',
    'Completed': 'Completado',
    'Cancelled': 'Cancelado',
    'In Progress': 'En progreso',
    'Queued': 'En cola',
    'Processing': 'Procesando',
    'Ready': 'Listo',
    'Active': 'Activo',
    'Inactive': 'Inactivo',
    'Enabled': 'Habilitado',
    'Disabled': 'Deshabilitado',
    'Online': 'En línea',
    'Offline': 'Sin conexión',
    'Busy': 'Ocupado',
    'Away': 'Ausente',
    'Available': 'Disponible',
    'Unavailable': 'No disponible',
    'Invite': 'Invitar',
    'Invitation': 'Invitación',
    'Accept': 'Aceptar',
    'Decline': 'Rechazar',
    'Join': 'Unirse',
    'Leave': 'Salir',
    'Enter': 'Entrar',
    'Exit': 'Salir',
    'Arrive': 'Llegar',
    'Depart': 'Partir',
    'Welcome': 'Bienvenido',
    'Goodbye': 'Adiós',
    'Hello': 'Hola',
    'Hi': 'Hola',
    'Hey': 'Hola',
    'Bye': 'Adiós',
    'See you': 'Hasta luego',
    'Take care': 'Cuídate',
    'Good luck': 'Buena suerte',
    'Have fun': 'Divértete',
    'Congratulations': 'Felicidades',
    'Happy birthday': 'Feliz cumpleaños',
    'Merry Christmas': 'Feliz Navidad',
    'Happy New Year': 'Feliz Año Nuevo',
    'Thank you': 'Gracias',
    'Thanks': 'Gracias',
    'Thank you very much': 'Muchas gracias',
    'Thanks a lot': 'Muchas gracias',
    'I appreciate it': 'Lo agradezco',
    'Sorry': 'Lo siento',
    'Apologize': 'Disculpe',
    'Excuse me': 'Disculpe',
    'Pardon': 'Perdón',
    'Forgive me': 'Perdóname',
    'No problem': 'Sin problema',
    'You are welcome': 'De nada',
    'My pleasure': 'Con mucho gusto',
    'Anytime': 'Cuando sea',
    'Do not mention it': 'No mention',
    'It is nothing': 'No es nada',
    'Think nothing of it': 'No lo pienses más',
    'Browse': 'Explorar',
    'Browse Templates': 'Explorar plantillas',
    'Official': 'Oficial',
    'Built-in': 'Integrado',
    'Community': 'Comunidad',
    'Personal': 'Personal',
    'Shared': 'Compartido',
    'Private': 'Privado',
    'Public': 'Público',
    'Published': 'Publicado',
    'Draft': 'Borrador',
    'Archived': 'Archivado',
    'Deleted': 'Eliminado',
    'Template': 'Plantilla',
    'Category': 'Categoría',
    'Tag': 'Etiqueta',
    'Label': 'Etiqueta',
    'Sort': 'Ordenar',
    'Filter': 'Filtrar',
    'Search': 'Buscar',
    'Find': 'Encontrar',
    'Group': 'Grupo',
    'View': 'Ver',
    'List': 'Lista',
    'Grid': 'Cuadrícula',
    'Table': 'Tabla',
    'Card': 'Tarjeta',
    'Map': 'Mapa',
    'Calendar': 'Calendario',
    'Timeline': 'Línea de tiempo',
    'Chart': 'Gráfico',
    'Graph': 'Gráfico',
    'Diagram': 'Diagrama',
    'Report': 'Informe',
    'Summary': 'Resumen',
    'Details': 'Detalles',
    'Overview': 'Resumen',
    'Preview': 'Vista previa',
    'Full': 'Completo',
    'Full screen': 'Pantalla completa',
    'Exit full screen': 'Salir de pantalla completa',
    'Maximize': 'Maximizar',
    'Minimize': 'Minimizar',
    'Restore': 'Restaurar',
    'Close': 'Cerrar',
    'Open': 'Abrir',
    'Collapse': 'Contraer',
    'Expand': 'Expandir',
    'Zoom in': 'Acercar',
    'Zoom out': 'Alejar',
    'Rotate': 'Rotar',
    'Flip': 'Voltear',
    'Download': 'Descargar',
    'Upload': 'Subir',
    'Import': 'Importar',
    'Export': 'Exportar',
    'Backup': 'Copia de seguridad',
    'Restore': 'Restaurar',
    'Save': 'Guardar',
    'Load': 'Cargar',
    'Clear': 'Limpiar',
    'Reset': 'Restablecer',
    'Undo': 'Deshacer',
    'Redo': 'Rehacer',
    'Copy': 'Copiar',
    'Paste': 'Pegar',
    'Cut': 'Cortar',
    'Delete': 'Eliminar',
    'Duplicate': 'Duplicar',
    'Rename': 'Renombrar',
    'Move': 'Mover',
    'Share': 'Compartir',
    'Send': 'Enviar',
    'Receive': 'Recibir',
    'Forward': 'Reenviar',
    'Reply': 'Responder',
    'Reply All': 'Responder a todos',
    'CC': 'CC',
    'BCC': 'BCC',
    'Subject': 'Asunto',
    'Body': 'Cuerpo',
    'Attachment': 'Adjunto',
    'Attachments': 'Adjuntos',
    'Send': 'Enviar',
    'Discard': 'Descartar',
    'Draft': 'Borrador',
    'From': 'De',
    'To': 'A',
    'CC': 'CC',
    'BCC': 'BCC',
    'Reply-To': 'Responder a',
    'Return-Path': 'Ruta de retorno',
    'Date': 'Fecha',
    'Time': 'Hora',
    'Timezone': 'Zona horaria',
    'Read': 'Leído',
    'Unread': 'No leído',
    'Starred': 'Marcado',
    'Unstarred': 'Sin marcar',
    'Important': 'Importante',
    'Not important': 'No importante',
    'Spam': 'Spam',
    'Not spam': 'No es spam',
    'Archive': 'Archivar',
    'Inbox': 'Bandeja de entrada',
    'Sent': 'Enviado',
    'Drafts': 'Borradores',
    'Trash': 'Papelera',
    'All Mail': 'Todo el correo',
    'Mark as read': 'Marcar como leído',
    'Mark as unread': 'Marcar como no leído',
    'Mark as important': 'Marcar como importante',
    'Mark as not important': 'Marcar como no importante',
    'Add star': 'Agregar estrella',
    'Remove star': 'Quitar estrella',
    'Move to': 'Mover a',
    'Copy to': 'Copiar a',
    'Label as': 'Etiquetar como',
    'Remove label': 'Quitar etiqueta',
    'Add to': 'Agregar a',
    'Remove from': 'Quitar de',
    'Subscribe': 'Suscribirse',
    'Unsubscribe': 'Cancelar suscripción',
    'Follow': 'Seguir',
    'Unfollow': 'Dejar de seguir',
    'Like': 'Me gusta',
    'Unlike': 'No me gusta',
    'Share': 'Compartir',
    'Comment': 'Comentario',
    'Comments': 'Comentarios',
    'Reply': 'Responder',
    'Replies': 'Respuestas',
    'Thread': 'Hilo',
    'Topic': 'Tema',
    'Post': 'Publicación',
    'Posts': 'Publicaciones',
    'Status': 'Estado',
    'Update': 'Actualización',
    'Check in': 'Registrarse',
    'Location': 'Ubicación',
    'Mood': 'Estado de ánimo',
    'Photo': 'Foto',
    'Tag': 'Etiqueta',
    'Mention': 'Mención',
    'Like': 'Me gusta',
    'Enjoy': 'Disfrutar',
    'Love': 'Amor',
    'Hate': 'Odio',
    'Wish': 'Desear',
    'Hope': 'Esperar',
    'Confirm': 'Confirmar',
    'Verified': 'Verificado',
    'Not verified': 'No verificado',
    'Pending verification': 'Verificación pendiente',
    'Restricted': 'Restringido',
    'Suspended': 'Suspendido',
    'Banned': 'Prohibido',
    'Muted': 'Silenciado',
    'Blocked': 'Bloqueado',
    'Reported': 'Reportado',
    'Copyright': 'Derechos de autor',
    'Trademark': 'Marca registrada',
    'Patent': 'Patente',
    'License': 'Licencia',
    'Terms of service': 'Términos de servicio',
    'Terms and conditions': 'Términos y condiciones',
    'Privacy policy': 'Política de privacidad',
    'Cookie policy': 'Política de cookies',
    'Accept': 'Aceptar',
    'Decline': 'Rechazar',
    'Agree': 'Aceptar',
    'Disagree': 'No aceptar',
    'Accept terms': 'Aceptar términos',
    'Decline terms': 'Rechazar términos',
    'I agree': 'Estoy de acuerdo',
    'I disagree': 'No estoy de acuerdo',
    'Accept cookies': 'Aceptar cookies',
    'Reject cookies': 'Rechazar cookies',
    'Manage cookies': 'Gestionar cookies',
    'Cookie settings': 'Configuración de cookies',
    'Privacy settings': 'Configuración de privacidad',
    'Notification settings': 'Configuración de notificaciones',
    'Email settings': 'Configuración de correo',
    'Account settings': 'Configuración de cuenta',
    'Profile settings': 'Configuración de perfil',
    'App settings': 'Configuración de la aplicación',
    'System settings': 'Configuración del sistema',
    'Language settings': 'Configuración de idioma',
    'Display settings': 'Configuración de pantalla',
    'Sound settings': 'Configuración de sonido',
    'Accessibility settings': 'Configuración de accesibilidad',
    'Data settings': 'Configuración de datos',
    'Security settings': 'Configuración de seguridad',
    'API settings': 'Configuración de API',
    'Developer settings': 'Configuración de desarrollador',
    'Advanced settings': 'Configuración avanzada',
    'Expert settings': 'Configuración de experto',
    'Debug settings': 'Configuración de depuración',
    'Beta features': 'Funciones beta',
    'Experimental features': 'Funciones experimentales',
    'New features': 'Nuevas funciones',
    'Coming soon': 'Próximamente',
    'Under development': 'En desarrollo',
    'Work in progress': 'Trabajo en progreso',
    'Planned': 'Planificado',
    'Considered': 'Considerado',
    'Requested': 'Solicitado',
    'Popular': 'Popular',
    'Trending': 'Tendencias',
    'Featured': 'Destacado',
    'Recommended': 'Recomendado',
    'Suggested': 'Sugerido',
    'Related': 'Relacionado',
    'Similar': 'Similar',
    'Compatible': 'Compatible',
    'Incompatible': 'Incompatible',
    'Supported': 'Soportado',
    'Unsupported': 'No soportado',
    'Required': 'Requerido',
    'Optional': 'Opcional',
    'Mandatory': 'Obligatorio',
    'Voluntary': 'Voluntario',
    'Free': 'Gratis',
    'Paid': 'De pago',
    'Freemium': 'Freemium',
    'Subscription': 'Suscripción',
    'One-time purchase': 'Compra única',
    'In-app purchase': 'Compra en la aplicación',
    'Trial': 'Prueba',
    'Demo': 'Demostración',
    'Beta': 'Beta',
    'Alpha': 'Alfa',
    'Stable': 'Estable',
    'LTS': 'LTS',
    'Nightly': 'Nocturna',
    'Canary': 'Canary',
    'Dev': 'Desarrollo',
    'Release': 'Lanzamiento',
    'Version': 'Versión',
    'Build': 'Compilación',
    'Revision': 'Revisión',
    'Commit': 'Confirmar',
    'Branch': 'Rama',
    'Tag': 'Etiqueta',
    'Merge': 'Combinar',
    'Fork': 'Bifurcar',
    'Clone': 'Clonar',
    'Pull': 'Extraer',
    'Push': 'Enviar',
    'Fetch': 'Obtener',
    'Checkout': 'Verificar',
    'Commit': 'Confirmar',
    'Revert': 'Revertir',
    'Rollback': 'Reversión',
    'Reset': 'Restablecer',
    'Stash': 'Guardar',
    'Pop': 'Sacar',
    'Apply': 'Aplicar',
    'Cherry-pick': 'Seleccionar',
    'Rebase': 'Reorganizar',
    'Amend': 'Enmendar',
    'Squash': 'Combinar',
    'Split': 'Dividir',
    'Diff': 'Diferencia',
    'Patch': 'Parche',
    'Conflict': 'Conflicto',
    'Resolve': 'Resolver',
    'Review': 'Revisar',
    'Approve': 'Aprobar',
    'Request changes': 'Solicitar cambios',
    'Comment': 'Comentario',
    'LGTM': 'Luce bien',
    'Ship it': 'Envíalo',
    'Test': 'Probar',
    'Tested': 'Probado',
    'Untested': 'No probado',
    'Pass': 'Aprobar',
    'Fail': 'Fallar',
    'Skip': 'Omitir',
    'Pending': 'Pendiente',
    'Blocked': 'Bloqueado',
    'Coverage': 'Cobertura',
    'Passed': 'Aprobado',
    'Failed': 'Fallido',
    'Broken': 'Roto',
    'Fixed': 'Corregido',
    'Known issue': 'Problema conocido',
    'Not a bug': 'No es un error',
    'Cannot reproduce': 'No se puede reproducir',
    'Works as designed': 'Funciona según lo diseñado',
    'Expected behavior': 'Comportamiento esperado',
    'Actual behavior': 'Comportamiento actual',
    'Steps to reproduce': 'Pasos para reproducir',
    'Additional info': 'Información adicional',
    'Environment': 'Entorno',
    'Browser': 'Navegador',
    'OS': 'Sistema operativo',
    'Device': 'Dispositivo',
    'App version': 'Versión de la aplicación',
    'Build number': 'Número de compilación',
    'User ID': 'ID de usuario',
    'Account ID': 'ID de cuenta',
    'Transaction ID': 'ID de transacción',
    'Order ID': 'ID de pedido',
    'Session ID': 'ID de sesión',
    'Request ID': 'ID de solicitud',
    'Correlation ID': 'ID de correlación',
    'Reference ID': 'ID de referencia',
    'Case number': 'Número de caso',
    'Ticket number': 'Número de ticket',
    'Issue number': 'Número de problema',
    'Bug number': 'Número de error',
    'PR number': 'Número de PR',
    'MR number': 'Número de MR',
    'Commit hash': 'Hash de confirmación',
    'Release version': 'Versión de lanzamiento',
    'Tag name': 'Nombre de etiqueta',
    'Milestone': 'Hito',
    'Sprint': 'Sprint',
    'Backlog': 'Pendientes',
    'Kanban': 'Kanban',
    'Scrum': 'Scrum',
    'Agile': 'Ágil',
    'Waterfall': 'Cascada',
    'DevOps': 'DevOps',
    'CI/CD': 'CI/CD',
    'Continuous integration': 'Integración continua',
    'Continuous deployment': 'Despliegue continuo',
    'Continuous delivery': 'Entrega continua',
    'Build server': 'Servidor de compilación',
    'Build agent': 'Agente de compilación',
    'Pipeline': 'Tubería',
    'Stage': 'Etapa',
    'Job': 'Trabajo',
    'Step': 'Paso',
    'Task': 'Tarea',
    'Worker': 'Trabajador',
    'Runner': 'Corredor',
    'Executor': 'Ejecutor',
    'Trigger': 'Disparador',
    'Webhook': 'Webhook',
    'Cron': 'Cron',
    'Schedule': 'Programación',
    'Artifact': 'Artefacto',
    'Artifact repository': 'Repositorio de artefactos',
    'Package': 'Paquete',
    'Package manager': 'Gestor de paquetes',
    'Dependency': 'Dependencia',
    'Dev dependency': 'Dependencia de desarrollo',
    'Peer dependency': 'Dependencia compartida',
    'Optional dependency': 'Dependencia opcional',
    'Transitive dependency': 'Dependencia transitiva',
    'Vulnerability': 'Vulnerabilidad',
    'Security vulnerability': 'Vulnerabilidad de seguridad',
    'Patch': 'Parche',
    'Hotfix': 'Corrección urgente',
    'Security patch': 'Parche de seguridad',
    'Update': 'Actualización',
    'Major update': 'Actualización mayor',
    'Minor update': 'Actualización menor',
    'Patch update': 'Actualización de parche',
    'Breaking change': 'Cambio importante',
    'Non-breaking change': 'Cambio no importante',
    'Deprecation': 'Descontinuación',
    'End of life': 'Fin de vida',
    'Sunset': 'Puesta de sol',
    'Maintenance': 'Mantenimiento',
    'Security': 'Seguridad',
    'Compliance': 'Cumplimiento',
    'Audit': 'Auditoría',
    'Backup': 'Copia de seguridad',
    'Disaster recovery': 'Recuperación de desastres',
    'Business continuity': 'Continuidad del negocio',
    'SLA': 'SLA',
    'Uptime': 'Tiempo de actividad',
    'Downtime': 'Tiempo de inactividad',
    'Maintenance window': 'Ventana de mantenimiento',
    'Planned maintenance': 'Mantenimiento planificado',
    'Emergency maintenance': 'Mantenimiento de emergencia',
    'Scheduled maintenance': 'Mantenimiento programado',
    'Incident': 'Incidente',
    'Outage': 'Interrupción',
    'Breach': 'Violación',
    'Attack': 'Ataque',
    'Threat': 'Amenaza',
    'Risk': 'Riesgo',
    'Issue': 'Problema',
    'Monitoring': 'Monitoreo',
    'Alert': 'Alerta',
    'Alarm': 'Alarma',
    'Notification': 'Notificación',
    'Dashboard': 'Panel',
    'Metrics': 'Métricas',
    'KPIs': 'KPIs',
    'Logs': 'Registros',
    'Traces': 'Rastreos',
    'Events': 'Eventos',
    'Health check': 'Verificación de salud',
    'Heartbeat': 'Latido del corazón',
    'Ping': 'Ping',
    'Status': 'Estado',
    'Operational': 'Operacional',
    'Degraded': 'Degradado',
    'Partial outage': 'Interrupción parcial',
    'Major outage': 'Interrupción mayor',
    'Under maintenance': 'En mantenimiento',
    'System OK': 'Sistema OK',
    'All systems operational': 'Todos los sistemas operacionales',
    'Partial system outage': 'Interrupción parcial del sistema',
    'Minor incident': 'Incidente menor',
    'Major incident': 'Incidente mayor',
    'Critical incident': 'Incidente crítico',
    'Emergency': 'Emergencia',
    'Urgent': 'Urgente',
    'High priority': 'Alta prioridad',
    'Medium priority': 'Prioridad media',
    'Low priority': 'Prioridad baja',
    'Urgent': 'Urgente',
    'Critical': 'Crítico',
    'Blocker': 'Bloqueador',
    'Must fix': 'Debe corregir',
    'Should fix': 'Debería corregir',
    'Could fix': 'Podría corregir',
    'Won\'t fix': 'No se corregirá',
    'Can\'t reproduce': 'No se puede reproducir',
    'Duplicate': 'Duplicado',
    'Not a bug': 'No es un error',
    'Works as designed': 'Funciona según lo diseñado',
    'Expected behavior': 'Comportamiento esperado',
    'As designed': 'Según diseño',
    'Closed': 'Cerrado',
    'Open': 'Abierto',
    'Reopened': 'Reabierto',
    'Resolved': 'Resuelto',
    'Verified': 'Verificado',
    'Acknowledged': 'Reconocido',
    'In review': 'En revisión',
    'In testing': 'En pruebas',
    'In development': 'En desarrollo',
    'Planned': 'Planificado',
    'Considered': 'Considerado',
    'Deferred': 'Diferido',
    'Ghost': 'Fantasma',
    'Not planned': 'No planificado',
    'Caption": "Subtítulos",
    "Captions": "Subtítulos",
    "Subtitles": "Subtítulos",
    "Audio track": "Pista de audio",
    "Video quality": "Calidad de video",
    "Auto quality": "Calidad automática",
    "High quality": "Alta calidad",
    "Medium quality": "Calidad media",
    "Low quality": "Baja calidad",
    "Battery": "Batería",
    "Battery level": "Nivel de batería",
    "Battery saver": "Ahorro de batería",
    "Power saving mode": "Modo de ahorro de energía",
    "Screen": "Pantalla",
    "Screen brightness": "Brillo de pantalla",
    "Screen timeout": "Tiempo de espera de pantalla",
    "Screen rotation": "Rotación de pantalla",
    "Screen lock": "Bloqueo de pantalla",
    "Volume": "Volumen",
    "Mute": "Silenciar",
    "Unmute": "Activar sonido",
    "Vibration": "Vibración",
    "Do not disturb": "No molestar",
    "Airplane mode": "Modo avión",
    "Bluetooth": "Bluetooth",
    "WiFi": "WiFi",
    "Mobile data": "Datos móviles",
    "Hotspot": "Punto de acceso",
    "GPS": "GPS",
    "Location services": "Servicios de ubicación",
    "NFC": "NFC",
    "Flashlight": "Linterna",
    "Camera": "Cámara",
    "Microphone": "Micrófono",
    "Storage": "Almacenamiento",
    "Memory": "Memoria",
    "RAM": "RAM",
    "Internal storage": "Almacenamiento interno",
    "External storage": "Almacenamiento externo",
    "SD card": "Tarjeta SD",
    "Clear cache": "Limpiar caché",
    "Clear data": "Limpiar datos",
    "Uninstall": "Desinstalar",
    "Force stop": "Forzar detención",
    "App info": "Información de la aplicación",
    "App permissions": "Permisos de la aplicación",
    "App version": "Versión de la aplicación",
    "Sign out": "Cerrar sesión",
    "Sign in": "Iniciar sesión",
    "Login": "Iniciar sesión",
    "Logout": "Cerrar sesión",
    "Register": "Registrarse",
    "Sign up": "Registrarse",
    "Forgot password": "¿Olvidó su contraseña?",
    "Reset password": "Restablecer contraseña",
    "Change password": "Cambiar contraseña",
    "Current password": "Contraseña actual",
    "New password": "Nueva contraseña",
    "Confirm password": "Confirmar contraseña",
    "Password changed": "Contraseña cambiada",
    "Password reset": "Restablecimiento de contraseña",
    "Password requirements": "Requisitos de contraseña",
    "Weak password": "Contraseña débil",
    "Strong password": "Contraseña fuerte",
    "Show password": "Mostrar contraseña",
    "Hide password": "Ocultar contraseña",
    "Remember me": "Recordarme",
    "Forgot username": "¿Olvidó su nombre de usuario?",
    "Username": "Nombre de usuario",
    "Email": "Correo electrónico",
    "Phone number": "Número de teléfono",
    "Verify": "Verificar",
    "Verified": "Verificado",
    "Unverified": "No verificado",
    "Verification": "Verificación",
    "Verification code": "Código de verificación",
    "Resend code": "Reenviar código",
    "Verification email": "Correo de verificación",
    "Verification required": "Verificación requerida",
    "Two-factor authentication": "Autenticación de dos factores",
    "2FA": "2FA",
    "TOTP": "TOTP",
    "SMS verification": "Verificación por SMS",
    "Email verification": "Verificación por correo",
    "Phone verification": "Verificación por teléfono",
    "Identity verification": "Verificación de identidad",
    "KYC": "KYC",
    "Age verification": "Verificación de edad",
    "Captcha": "Captcha",
    "Recaptcha": "Recaptcha",
    "Security question": "Pregunta de seguridad",
    "Security answer": "Respuesta de seguridad",
    "Backup codes": "Códigos de respaldo",
    "Recovery codes": "Códigos de recuperación",
    "Emergency codes": "Códigos de emergencia",
    "One-time password": "Contraseña de un solo uso",
    "OTP": "OTP",
    "Magic link": "Enlace mágico",
    "Passwordless": "Sin contraseña",
    "Biometric": "Biométrico",
    "Fingerprint": "Huella digital",
    "Face ID": "Face ID",
    "Touch ID": "Touch ID",
    "Face unlock": "Desbloqueo facial",
    "Fingerprint unlock": "Desbloqueo por huella",
    "PIN": "PIN",
    "Pattern": "Patrón",
    "Lock screen": "Pantalla de bloqueo",
    "App lock": "Bloqueo de aplicación",
    "Content blocker": "Bloqueador de contenido",
    "Ad blocker": "Bloqueador de anuncios",
    "Parental controls": "Controles parentales",
    "Screen time": "Tiempo de pantalla",
    "Digital wellbeing": "Bienestar digital",
    "Focus mode": "Modo enfoque",
    "Dark mode": "Modo oscuro",
    "Light mode": "Modo claro",
    "System default": "Predeterminado del sistema",
    "Auto dark mode": "Modo oscuro automático",
    "Scheduled": "Programado",
    "Sunset to sunrise": "Del atardecer al amanecer",
    "Custom schedule": "Programa personalizado",
    "Night Light": "Luz nocturna",
    "Blue light filter": "Filtro de luz azul",
    "Color temperature": "Temperatura del color",
    "Warm": "Cálido",
    "Cool": "Frío",
    "Normal": "Normal",
    "Grayscale": "Escala de grises",
    "Inverted": "Invertido",
    "High contrast": "Alto contraste",
    "Large text": "Texto grande",
    "Bold text": "Texto en negrita",
    "Reduce motion": "Reducir movimiento",
    "Auto-play": "Reproducción automática",
    "Analytics": "Análisis",
    "Crash reports": "Reports de errores",
    "Usage statistics": "Estadísticas de uso",
    "Feedback reports": "Reports de comentarios",
    "Diagnostic data": "Datos de diagnóstico",
    "Share analytics": "Compartir análisis",
    "Tailored experience": "Experiencia personalizada",
    "Personalization": "Personalización",
    "Recommendations": "Recomendaciones",
    "Suggestions": "Sugerencias",
    "For you": "Para ti",
    "Discover": "Descubrir",
    "Explore": "Explorar",
    "Trending": "Tendencias",
    "Popular": "Popular",
    "Featured": "Destacado",
    "Top": "Superior",
    "Best": "Mejor",
    "New": "Nuevo",
    "Latest": "Último",
    "Recently added": "Agregado recientemente",
    "Recently updated": "Actualizado recientemente",
    "Coming soon": "Próximamente",
    "Pre-register": "Pre-registro",
    "Pre-order": "Pre-pedido",
    "Launch": "Lanzamiento",
    "Release date": "Fecha de lanzamiento",
    "Announced": "Anunciado",
    "Rumored": "Rumoreado",
    "Speculated": "Especulado",
    "Confirmed": "Confirmado",
    "Unconfirmed": "No confirmado",
    "Official": "Oficial",
    "Unofficial": "No oficial",
    "Leaked": "Filtrado",
    "Preview": "Vista previa",
    "Beta": "Beta",
    "Alpha": "Alfa",
    "Release candidate": "Candidato a lanzamiento",
    "Stable": "Estable",
    "LTS": "LTS",
    "Nightly": "Nocturna",
    "Canary": "Canary",
    "Dev": "Desarrollo",
    "Experimental": "Experimental",
    "Preview": "Vista previa",
    "Early access": "Acceso anticipado",
    "Access": "Acceso",
    "Grant access": "Otorgar acceso",
    "Revoke access": "Revocar acceso",
    "Request access": "Solicitar acceso",
    "Access granted": "Acceso concedido",
    "Access denied": "Acceso denegado",
    "Access revoked": "Acceso revocado",
    "Access pending": "Acceso pendiente",
    "Read access": "Acceso de lectura",
    "Write access": "Acceso de escritura",
    "Full access": "Acceso completo",
    "Limited access": "Acceso limitado",
    "No access": "Sin acceso",
    "Guest access": "Acceso de invitado",
    "Admin access": "Acceso de administrador",
    "Root access": "Acceso root",
    "Superuser": "Superusuario",
    "Moderator": "Moderador",
    "Editor": "Editor",
    "Viewer": "Visor",
    "Contributor": "Contribuidor",
    "Author": "Autor",
    "Owner": "Propietario",
    "Maintainer": "Mantenedor",
    "Reviewer": "Revisor",
    "Approver": "Aprobador",
    'E-Claw': 'E-Claw',
    'EClawbot': 'EClawbot',
    'OpenClaw': 'OpenClaw',
};

// Simple word-based translation for strings that don't match patterns
function translateToSpanish(text) {
    if (!text) return '';
    
    // If it's in our patterns, return the translation
    if (spanishPatterns[text]) {
        return spanishPatterns[text];
    }
    
    // Try some common replacements
    let result = text;
    
    // Handle template variables like {name}, {{name}}, {count}, etc.
    // Keep them as-is
    result = result.replace(/\{[^}]+\}/g, match => match);
    
    return result;
}

// Load missing pairs
const missingData = JSON.parse(fs.readFileSync('missing_pairs.json', 'utf8'));
console.log(`Processing ${missingData.length} missing translations`);

// Translate each
const translations = {};
let successCount = 0;
let fallbackCount = 0;

for (const item of missingData) {
    const translated = translateToSpanish(item.en);
    if (translated !== item.en) {
        successCount++;
    } else {
        fallbackCount++;
    }
    translations[item.key] = translated;
}

console.log(`Direct translations: ${successCount}`);
console.log(`Fallback (EN unchanged): ${fallbackCount}`);

// Save
fs.writeFileSync('es_translations_generated.json', JSON.stringify(translations, null, 2));
console.log('Saved to es_translations_generated.json');
