'use strict';

const express = require('express');
const crypto = require('crypto');
const path = require('path');
const { isDeepStrictEqual } = require('util');
const safeEqual = require('./safe-equal');
const CodexPluginStore = require('./codex-plugin-store');
const { withCreationLock } = require('./codex-plugin-creation-lock');

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const PROFILES = ['read-only', 'workspace-write'];
const MCP_VERSIONS = ['2025-11-25', '2025-06-18', '2025-03-26'];
const objectSchema = properties => ({ type: 'object', properties, additionalProperties: false });
const string = { type: 'string' };
const bindingSchema = { binding_id: { type: 'string', format: 'uuid' } };
const configSchema = {
    role: string, instructions: string, language: string,
    permission_profile: { type: 'string', enum: PROFILES },
    customer_service_enabled: { type: 'boolean' }, customer_knowledge: string
};
const TOOL_DEFINITIONS = [
    ['get_profile', 'Identify the connected EClaw account.', {}, [], true],
    ['list_codex_entities', 'List your Codex entities and current connection state.', {}, [], true],
    ['create_codex_entity', 'Create an EClaw entity for an existing local Codex thread. Requires enrollment of a running local Codex helper; creation alone does not make it online.', {
        name: string, thread_id: string, workspace: string, request_id: { type: 'string', format: 'uuid' }, ...configSchema
    }, ['name', 'thread_id', 'workspace', 'request_id'], false],
    ['approve_runtime', 'Approve the local enrollment generated by the bundled helper for your entity. Only approve an enrollment from the connect workflow you requested.', {
        ...bindingSchema, enrollment_id: { type: 'string', format: 'uuid' }
    }, ['binding_id', 'enrollment_id'], false],
    ['configure_codex_entity', 'Change your entity role, published customer knowledge or local Codex permission profile. Changes apply to subsequent turns.', {
        ...bindingSchema, ...configSchema
    }, ['binding_id'], false],
    ['disconnect_codex_entity', 'Revoke the local runtime connection. Retains the EClaw entity and chat history; stops remote control.', bindingSchema, ['binding_id'], false],
    ['read_codex_logs', 'Read connection and approval events for your own Codex entity.', {
        ...bindingSchema, limit: { type: 'integer', minimum: 1, maximum: 100 }
    }, ['binding_id'], true]
].map(([name, description, properties, required, readOnly]) => ({
    name, description, inputSchema: { ...objectSchema(properties), required },
    annotations: { readOnlyHint: readOnly, destructiveHint: false, openWorldHint: false, idempotentHint: true },
    securitySchemes: [{ type: 'oauth2', scopes: [readOnly ? 'codex:read' : 'codex:manage'] }]
}));

function error(status, message) { return Object.assign(new Error(message), { status }); }
function uuid(value, name) { if (typeof value !== 'string' || !UUID.test(value)) throw error(400, `Invalid ${name}`); return value; }
function text(value, name, max, required = false) {
    if (value === undefined && !required) return undefined;
    if (typeof value !== 'string' || value.length > max || (required && !value.trim()) || value.includes('\0')) throw error(400, `Invalid ${name}`);
    return value;
}
function validateConfig(args, original = {}) {
    const config = { ...original };
    for (const [key, target, max] of [['role', 'role', 2000], ['instructions', 'instructions', 12000], ['language', 'language', 32], ['customer_knowledge', 'customerKnowledge', 30000]]) {
        if (args[key] !== undefined) config[target] = text(args[key], key, max);
    }
    if (args.permission_profile !== undefined) {
        if (!PROFILES.includes(args.permission_profile)) throw error(400, 'Unsupported permission profile');
        config.permissionProfile = args.permission_profile;
    }
    if (args.customer_service_enabled !== undefined) {
        if (typeof args.customer_service_enabled !== 'boolean') throw error(400, 'Invalid customer_service_enabled');
        config.customerServiceEnabled = args.customer_service_enabled;
    }
    if (config.customerServiceEnabled && !config.customerKnowledge?.trim()) throw error(400, 'Customer service requires published knowledge');
    return config;
}

function normalizeMessage(raw) {
    const owner = raw.codexOwner === true;
    const external = !owner && typeof raw.fromPublicCode === 'string';
    return {
        id: raw.codexDeliveryId || crypto.randomUUID(), text: String(raw.text || '').slice(0, 30000),
        owner, timestamp: raw.timestamp || Date.now(),
        ...(external && { customerKey: raw.fromPublicCode }),
        ...(external && { senderHint: { kind: 'entity', publicCode: raw.fromPublicCode } }),
        ...(owner && raw.ask_id && { ask_id: raw.ask_id, action_id: raw.action_id, answers: raw.answers })
    };
}

function createCodexPlugin({ pool, devices, db, oauth, invokeApi, sendOwnerNotice, saveData, persistDevice = async () => {}, io, serverLog, baseUrl = 'https://eclawbot.com', store = new CodexPluginStore(pool), allowedOrigins = [new URL(baseUrl).origin, 'https://chatgpt.com'] }) {
    const runtimeRouter = express.Router();
    const locks = new Map();
    const enrollmentAttempts = new Map();
    const ready = store.initDatabase();
    // Prevent an unhandled startup rejection; requests still fail closed on ready.
    ready.catch(() => {});

    async function serialized(key, fn) {
        const previous = locks.get(key) || Promise.resolve();
        const next = previous.catch(() => {}).then(fn);
        locks.set(key, next);
        try { return await next; } finally { if (locks.get(key) === next) locks.delete(key); }
    }
    function audit(binding, action) {
        serverLog?.('info', 'codex_plugin', action, { deviceId: binding.device_id, entityId: binding.entity_id, metadata: { bindingId: binding.id } });
    }
    function entityFor(binding) {
        const entity = devices[binding.device_id]?.entities?.[binding.entity_id];
        if (!entity?.isBound || entity.channelAccountId !== binding.channel_account_id) throw error(409, 'Entity binding has changed');
        return entity;
    }
    function describe(binding) {
        const config = binding.config;
        const entity = binding.entity_id === null ? null : devices[binding.device_id]?.entities?.[binding.entity_id];
        let state = 'offline';
        if (entity?.isBound && entity.channelAccountId === binding.channel_account_id && !binding.disconnected && Number(binding.heartbeat_at) > Date.now() - 45000) state = binding.runtime_state;
        return {
            id: binding.id, entityId: binding.entity_id, name: entity?.name || config.name,
            threadId: config.threadId, workspace: config.workspace,
            role: config.role || '', instructions: config.instructions || '', language: config.language || 'zh-TW',
            permissionProfile: config.permissionProfile, customerServiceEnabled: !!config.customerServiceEnabled,
            customerKnowledge: config.customerKnowledge || '', state,
            disconnected: !!binding.disconnected, publicCode: entity?.publicCode || null,
            chatUrl: `${baseUrl}/portal/chat.html?entityId=${binding.entity_id}`
        };
    }
    async function owned(deviceId, id) {
        const binding = await store.binding(uuid(id, 'binding_id'));
        if (!binding || binding.device_id !== deviceId || !devices[deviceId]) throw error(404, 'Codex entity not found');
        return binding;
    }
    function bearerHash(req) {
        const match = /^Bearer ([A-Za-z0-9_-]{32,128})$/.exec(req.headers.authorization || '');
        if (!match) throw error(401, 'Runtime authentication required');
        return crypto.createHash('sha256').update(match[1]).digest('hex');
    }
    async function authenticatedRuntime(req) {
        const binding = await store.binding(uuid(req.query.bindingId || req.body.bindingId, 'bindingId'));
        if (!binding || binding.disconnected || !binding.runtime_token_hash || !safeEqual(binding.runtime_token_hash, bearerHash(req))) throw error(401, 'Invalid runtime credentials');
        entityFor(binding);
        return binding;
    }
    async function account(binding) {
        const result = await db.getChannelAccountById(binding.channel_account_id);
        if (!result || result.device_id !== binding.device_id) throw error(409, 'Channel account unavailable');
        return result;
    }
    async function createEntity(deviceId, args) {
        text(args.name, 'name', 20, true);
        text(args.thread_id, 'thread_id', 128, true);
        text(args.workspace, 'workspace', 2048, true);
        if (!path.posix.isAbsolute(args.workspace) && !path.win32.isAbsolute(args.workspace)) throw error(400, 'Workspace must be absolute');
        uuid(args.request_id, 'request_id');
        const config = validateConfig(args, { name: args.name, threadId: args.thread_id, workspace: args.workspace, permissionProfile: 'read-only', customerServiceEnabled: false });
        return serialized(deviceId, () => withCreationLock(pool, deviceId, async () => {
            let binding = await store.begin(deviceId, args.request_id, config);
            if (binding.disconnected) throw error(409, 'Use a new request_id for a new connection');
            // Reject reuse of an idempotency key with different intent.
            if (!isDeepStrictEqual(binding.config, config)) throw error(409, 'request_id already used with different settings');
            if (binding.entity_id !== null) return describe(binding);
            if (!binding.channel_account_id) {
                await persistDevice(deviceId);
                await store.provisionAccount(binding.id, deviceId);
                binding = await store.binding(binding.id);
            }
            const channel = await account(binding);
            const bound = await invokeApi('/api/channel/bind', { channel_api_key: channel.channel_api_key, name: config.name });
            await store.setEntity(binding.id, bound.entityId);
            binding = await store.binding(binding.id);
            audit(binding, 'Codex entity created; awaiting local runtime');
            return describe(binding);
        }));
    }
    async function callTool(principal, name, args) {
        await ready;
        if (!devices[principal.deviceId]) throw error(403, 'Connected device unavailable');
        switch (name) {
        case 'get_profile': return { deviceId: principal.deviceId, displayName: devices[principal.deviceId].name || 'EClaw account' };
        case 'list_codex_entities': return { entities: (await store.list(principal.deviceId)).map(describe) };
        case 'create_codex_entity': return createEntity(principal.deviceId, args);
        case 'approve_runtime': {
            const binding = await owned(principal.deviceId, args.binding_id);
            if (binding.disconnected) throw error(409, 'Connection is disconnected');
            entityFor(binding);
            const enrollment = await store.enrollment(uuid(args.enrollment_id, 'enrollment_id'), binding.id);
            if (!enrollment || Number(enrollment.expires_at) <= Date.now()) throw error(404, 'Enrollment unavailable or expired');
            if (enrollment.thread_id !== binding.config.threadId || enrollment.workspace !== binding.config.workspace) throw error(409, 'Enrollment does not match the selected Codex thread and workspace');
            if (!(enrollment.approved && safeEqual(binding.runtime_token_hash || '', enrollment.token_hash))) await store.approve(binding, enrollment);
            audit(binding, 'Local runtime enrollment approved');
            return describe(await store.binding(binding.id));
        }
        case 'configure_codex_entity': {
            const binding = await owned(principal.deviceId, args.binding_id);
            if (binding.disconnected) throw error(409, 'Connection is disconnected');
            const config = validateConfig(args, binding.config);
            await store.configure(binding.id, config);
            audit(binding, 'Codex entity configuration updated');
            return describe(await store.binding(binding.id));
        }
        case 'disconnect_codex_entity': {
            const binding = await owned(principal.deviceId, args.binding_id);
            await store.disconnect(binding.id);
            audit(binding, 'Local runtime connection revoked');
            return describe(await store.binding(binding.id));
        }
        case 'read_codex_logs': {
            const binding = await owned(principal.deviceId, args.binding_id);
            const limit = args.limit ?? 30;
            if (!Number.isInteger(limit) || limit < 1 || limit > 100) throw error(400, 'Invalid limit');
            const logs = (await pool.query(
                `SELECT level,message,created_at FROM server_logs WHERE device_id=$1 AND entity_id=$2 AND category='codex_plugin' ORDER BY created_at DESC LIMIT $3`,
                [binding.device_id, binding.entity_id, limit])).rows;
            return { logs };
        }
        default: throw error(404, 'Unknown tool');
        }
    }

    async function mcpHandler(req, res) {
        res.set('Cache-Control', 'no-store');
        if (req.headers.origin && !allowedOrigins.includes(req.headers.origin)) return res.status(403).json({ success: false, error: 'invalid_origin' });
        if (req.headers['mcp-protocol-version'] && !MCP_VERSIONS.includes(req.headers['mcp-protocol-version'])) return res.status(400).json({ success: false, error: 'unsupported_protocol_version' });
        if (req.method !== 'POST') return res.status(405).set('Allow', 'POST').end();
        try {
            await ready;
            const principal = await oauth.authenticateBearer(req, []);
            const body = req.body;
            if (!body || Array.isArray(body) || body.jsonrpc !== '2.0' || typeof body.method !== 'string') return res.status(400).json({ jsonrpc: '2.0', id: null, error: { code: -32600, message: 'Invalid Request' } });
            const response = result => res.json({ jsonrpc: '2.0', id: body.id ?? null, result });
            if (body.method.startsWith('notifications/')) return res.status(202).end();
            if (body.method === 'initialize') return response({ protocolVersion: MCP_VERSIONS.includes(body.params?.protocolVersion) ? body.params.protocolVersion : MCP_VERSIONS[0], capabilities: { tools: {} }, serverInfo: { name: 'eclawbot', version: '0.1.0' }, instructions: 'EClaw controls an enrolled local Codex runtime. A newly created entity remains offline until the helper connects.' });
            if (body.method === 'ping') return response({});
            if (body.method === 'tools/list') return response({ tools: TOOL_DEFINITIONS });
            if (body.method !== 'tools/call') return res.json({ jsonrpc: '2.0', id: body.id ?? null, error: { code: -32601, message: 'Method not found' } });
            const tool = TOOL_DEFINITIONS.find(t => t.name === body.params?.name);
            if (!tool) return res.json({ jsonrpc: '2.0', id: body.id ?? null, error: { code: -32602, message: 'Unknown tool' } });
            const args = body.params.arguments ?? {};
            if (!args || Array.isArray(args) || typeof args !== 'object' || Object.keys(args).some(k => !(k in tool.inputSchema.properties)) || tool.inputSchema.required.some(k => args[k] === undefined)) throw error(400, 'Invalid tool arguments');
            await oauth.authenticateBearer(req, tool.securitySchemes[0].scopes);
            try {
                const result = await callTool(principal, tool.name, args);
                return response({ content: [{ type: 'text', text: JSON.stringify(result) }], structuredContent: result, isError: false });
            } catch (failure) {
                return response({ content: [{ type: 'text', text: failure.status ? failure.message : 'EClaw operation unavailable. Retry with the same request_id.' }], isError: true });
            }
        } catch (failure) {
            const status = failure.status || 503;
            if (status === 401) res.set('WWW-Authenticate', `Bearer resource_metadata="${baseUrl}/.well-known/oauth-protected-resource"`);
            return res.status(status).json({ success: false, error: status === 401 ? 'unauthorized' : status === 403 ? 'insufficient_scope' : status === 400 ? 'invalid_request' : 'service_unavailable' });
        }
    }

    runtimeRouter.use(async (_req, res, next) => {
        res.set('Cache-Control', 'no-store');
        try { await ready; next(); } catch (_) { res.status(503).json({ success: false, error: 'codex_unavailable' }); }
    });
    function route(method, url, fn) {
        runtimeRouter[method](url, async (req, res) => {
            try { res.json({ success: true, ...await fn(req) }); }
            catch (failure) {
                const status = failure.status || 503;
                const code = { 400: 'invalid_request', 401: 'runtime_unauthorized', 403: 'forbidden',
                    404: 'not_found', 409: 'binding_conflict', 410: 'enrollment_expired', 429: 'rate_limited' }[status] || 'codex_unavailable';
                res.status(status).json({ success: false, error: code, ...(failure.status && { message: failure.message }) });
            }
        });
    }
    route('post', '/enroll', async req => {
        const ip = req.ip || 'unknown';
        const prior = enrollmentAttempts.get(ip);
        const bucket = !prior || Date.now() - prior.start > 60000 ? { start: Date.now(), count: 0 } : prior;
        bucket.count++; enrollmentAttempts.set(ip, bucket);
        if (enrollmentAttempts.size > 10000) for (const [key, item] of enrollmentAttempts) if (Date.now() - item.start > 60000) enrollmentAttempts.delete(key);
        if (bucket.count > 15) throw error(429, 'Enrollment rate limit reached');
        const binding = await store.binding(uuid(req.body.bindingId, 'bindingId'));
        if (!binding || binding.disconnected) throw error(404, 'Connection unavailable');
        if (!/^[0-9a-f]{64}$/.test(req.body.tokenHash || '')) throw error(400, 'Invalid tokenHash');
        if (req.body.threadId !== binding.config.threadId || req.body.workspace !== binding.config.workspace) throw error(409, 'Thread and workspace do not match');
        const enrollment = await store.enroll(binding.id, req.body.tokenHash, req.body.threadId, req.body.workspace);
        return { enrollmentId: enrollment.id, expiresAt: Number(enrollment.expires_at) };
    });
    route('get', '/enrollment', async req => {
        const binding = await store.binding(uuid(req.query.bindingId, 'bindingId'));
        const enrollment = await store.enrollment(uuid(req.query.enrollmentId, 'enrollmentId'), req.query.bindingId);
        const hash = bearerHash(req);
        if (!binding || binding.disconnected || !enrollment || !safeEqual(enrollment.token_hash, hash)) throw error(401, 'Invalid enrollment credentials');
        const approved = enrollment.approved && safeEqual(binding.runtime_token_hash || '', hash);
        if (!approved && Number(enrollment.expires_at) <= Date.now()) throw error(410, 'Enrollment expired');
        return { approved, ...(approved && { binding: describe(binding) }) };
    });
    route('get', '/poll', async req => {
        const binding = await authenticatedRuntime(req);
        return serialized(binding.id, async () => {
            const entity = entityFor(binding);
            const queue = entity.messageQueue || [];
            const hadMessages = queue.length > 0;
            for (const message of [...queue]) {
                if (message.from === 'system' && !message.codexOwner) { queue.splice(queue.indexOf(message), 1); continue; }
                message.codexDeliveryId ||= crypto.randomUUID();
                await store.enqueue(binding.id, normalizeMessage(message));
                queue.splice(queue.indexOf(message), 1);
            }
            if (queue.length === 0) entity.lastDrainedAt = Date.now();
            if (hadMessages) await saveData();
            await store.heartbeat(binding.id, req.query.busy === 'true' ? 'busy' : 'online');
            return { binding: describe(await store.binding(binding.id)), messages: await store.pending(binding.id) };
        });
    });
    route('post', '/heartbeat', async req => {
        const binding = await authenticatedRuntime(req);
        if (!['online', 'offline', 'busy'].includes(req.body.state)) throw error(400, 'Invalid runtime state');
        await store.heartbeat(binding.id, req.body.state);
        const entity = entityFor(binding);
        entity.state = req.body.state === 'busy' ? 'BUSY' : 'IDLE';
        entity.lastUpdated = Date.now();
        io?.to(`device:${binding.device_id}`).emit('entity:update', {
            entityId: binding.entity_id, state: entity.state, name: entity.name,
            message: entity.message, lastUpdated: entity.lastUpdated
        });
        if (req.body.lastError) audit(binding, 'Local runtime reported an error; check the local helper');
        return { binding: describe(await store.binding(binding.id)) };
    });
    route('post', '/ack', async req => {
        const binding = await authenticatedRuntime(req);
        if (!Array.isArray(req.body.messageIds) || req.body.messageIds.length > 20) throw error(400, 'Invalid messageIds');
        req.body.messageIds.forEach(id => uuid(id, 'messageId'));
        await store.complete(binding.id, req.body.messageIds);
        return {};
    });
    route('post', '/reply', async req => {
        const binding = await authenticatedRuntime(req);
        const message = text(req.body.message, 'message', 30000, true);
        const job = await store.job(uuid(req.body.replyTo, 'replyTo'), binding.id);
        if (!job) throw error(404, 'Message not found');
        if (job.completed_at) return { alreadyDelivered: true };
        return serialized(`${binding.id}:reply:${job.id}`, async () => {
            const latest = await store.job(job.id, binding.id);
            if (latest.completed_at) return { alreadyDelivered: true };
            if (job.payload.owner) await sendOwnerNotice(binding, message);
            else if (job.payload.senderHint?.kind === 'entity' && job.payload.senderHint.publicCode) {
                const channel = await account(binding);
                await invokeApi('/api/channel/message', {
                    channel_api_key: channel.channel_api_key, deviceId: binding.device_id, entityId: binding.entity_id,
                    botSecret: entityFor(binding).botSecret, state: 'IDLE', message,
                    // Explicit target wins over generated @mentions/@all in the
                    // existing channel API. A customer cannot redirect a reply.
                    senderHint: job.payload.senderHint, speakTo: [job.payload.senderHint.publicCode]
                });
            } else {
                // An unaddressable sender never shares a generic customer
                // thread or gains model-controlled broadcast routing.
                await sendOwnerNotice(binding, 'A customer message could not be routed. Contact the sender through EClaw.');
            }
            await store.complete(binding.id, [job.id], message);
            audit(binding, job.payload.owner ? 'Owner message answered by Codex' : 'Customer question answered by Codex');
            return {};
        });
    });
    route('post', '/approval', async req => {
        const binding = await authenticatedRuntime(req);
        const askId = text(req.body.askId, 'askId', 128, true);
        const body = text(req.body.body, 'body', 12000, true);
        const title = text(req.body.title, 'title', 200, true);
        const buttons = req.body.buttons;
        if (!Array.isArray(buttons) || buttons.length < 1 || buttons.length > 10) throw error(400, 'Invalid approval buttons');
        for (const button of buttons) { text(button.id, 'button id', 128, true); text(button.label, 'button label', 200, true); }
        await sendOwnerNotice(binding, body, { ask_id: askId, title, body, buttons });
        audit(binding, 'Codex requested owner approval');
        return {};
    });
    async function handleCardAction({ deviceId, entityId, askId, actionId, answers, ownerAuthenticated }) {
        await ready;
        const binding = (await store.list(deviceId)).find(row => row.entity_id === entityId && !row.disconnected);
        if (!binding) return false;
        entityFor(binding);
        if (!ownerAuthenticated) throw error(403, 'Only the owner can approve Codex actions');
        if (answers !== undefined && (!answers || typeof answers !== 'object' || Array.isArray(answers) || JSON.stringify(answers).length > 16000)) throw error(400, 'Invalid approval answers');
        await store.enqueue(binding.id, { owner: true, text: '', ask_id: askId, action_id: actionId,
            ...(answers !== undefined && { answers }), timestamp: Date.now() });
        audit(binding, 'Owner answered a Codex approval request');
        return true;
    }
    async function diagnostics(deviceId, limit = 30) {
        await ready;
        // Project only operational fields. Runtime/token hashes and transcript
        // payloads are never exposed, even through a development diagnostic.
        const bindings = await store.list(deviceId);
        const events = (await pool.query(
            "SELECT level,message,created_at FROM server_logs WHERE (device_id=$1 OR device_id IS NULL) AND category='codex_plugin' ORDER BY created_at DESC LIMIT $2",
            [deviceId, limit])).rows;
        return {
            bindings: bindings.map(row => ({ id: row.id, entityId: row.entity_id, state: describe(row).state,
                disconnected: row.disconnected, heartbeatAt: row.heartbeat_at, createdAt: row.created_at })), events
        };
    }
    return { mcpHandler, runtimeRouter, ready, handleCardAction, diagnostics, callTool, describe, store, tools: TOOL_DEFINITIONS };
}

module.exports = { createCodexPlugin, TOOL_DEFINITIONS, normalizeMessage, validateConfig };
